//! `nirdosha init <project-name>` scaffolding: pure text generation for
//! the starter `.nir` file and its launcher scripts (`docs/ROADMAP.md` Track
//! A6's proposed `init` command, and Track A2's "deployment story for the
//! interpreted path" for the self-contained-folder case). No filesystem
//! or process I/O lives here -- `main.rs::cmd_init` does the actual
//! writing (and bundles a copy of the running executable), the same
//! split `ui_gen::generate`/`cmd_emit_ui` already use.
//!
//! The two fixtures below (`email`/`sms`/`push` provider config, role
//! mapping) are copied verbatim from `scratch/nirdosha_llm_prompt.md`'s
//! "Standing fixtures -- emit once per project" section, which documents
//! them as already verified end-to-end (typecheck, `nirdosha serve`, live
//! CRUD via curl, real screens in the `emit-ui` manifest) -- this module
//! just emits that same text instead of an LLM hand-typing it per project.

/// Which standing fixtures to include. `email`/`roles` default on -- the
/// prompt file calls them the two panels "every generated project should
/// carry, regardless of which user stories are being processed."
/// `sms`/`push` are the identical provider-config shape as `email`,
/// opt-in per that doc's "add whichever channels the stories actually
/// use (don't add a channel no story needs)."
pub struct InitOptions {
    pub email: bool,
    pub roles: bool,
    pub sms: bool,
    pub push: bool,
}

impl Default for InitOptions {
    fn default() -> Self {
        InitOptions { email: true, roles: true, sms: false, push: false }
    }
}

/// Generates the starter `.nir` source for `project_name`. `Err` only if
/// `project_name` contains a `"` or a newline -- it's spliced directly
/// into `db_connect("<project_name>.db")` string literals below, and
/// either character would silently produce a `.nir` file that fails to
/// lex. Nothing else about the name needs validating.
pub fn generate_source(project_name: &str, opts: &InitOptions) -> Result<String, String> {
    if project_name.contains('"') || project_name.contains('\n') {
        return Err(format!(
            "project name {project_name:?} can't contain a `\"` or a newline -- \
             it's spliced into a db_connect(...) string literal in the generated source"
        ));
    }
    let db = format!("{project_name}.db");
    let mut out = header_comment(project_name);
    let any = opts.email || opts.sms || opts.push || opts.roles;
    if any {
        // Every fixture below returns `Result(_, Text)` -- `str` is
        // banned as a fn parameter/return type (docs/LANGUAGE.md's str-ban),
        // so free-text error messages cross a function boundary wrapped
        // in this one-field struct instead (`scratch/nirdosha_llm_prompt.md`
        // line ~132's documented convention). Declared exactly once here,
        // never per fixture.
        out.push_str(TEXT_STRUCT);
    }
    if opts.email {
        out.push_str(&provider_config_block("email", &db));
    }
    if opts.sms {
        out.push_str(&provider_config_block("sms", &db));
    }
    if opts.push {
        out.push_str(&provider_config_block("push", &db));
    }
    if opts.roles {
        out.push_str(&role_mapping_block(&db));
    }
    if !any {
        out.push_str("\n// no structs yet -- see the table above and add your first struct + create_/list_/... fns\n");
    }
    Ok(out)
}

fn header_comment(project_name: &str) -> String {
    format!(
        r#"// {project_name}.nir -- generated by `nirdosha init {project_name}`.
//
// Run it with `./run.sh` (or `run.bat` on Windows), which starts
// `nirdosha serve {project_name}.nir` -- a real HTTP service: the UI at
// GET /, the API at POST /api/<fn>. See run.sh for the exact flags
// (host/port, and placeholder --jwks-file/--issuer/--audience -- replace
// those once you have a real identity provider, or delete all three to
// run with no auth at all).
//
// Add your own structs and fns below. `nirdosha emit-ui`/`serve` infer a
// screen per struct from this naming convention -- get it right and the
// UI/API show up for free; a correct-but-differently-worded verb is
// invisible to the generated UI:
//
//   creates a new record          create_<entity>
//   lists/browses records         list_<entity>
//   fetches one record            get_<entity>
//   modifies a record             update_<entity>
//   removes a record              delete_<entity>
//   a numeric KPI                 stat_<name>() -> i64 | f64
//   a labeled series for a chart  chart_<name>() -> json  (rows shaped {{label, value}})
//
// Every db_connect(...) call in this file must use the exact same
// literal -- "{project_name}.db" below -- or two different SQLite files
// end up in play and every mismatched call fails with "no such table".
"#
    )
}

const TEXT_STRUCT: &str = "\nstruct Text {\n    value: str,\n}\n";

/// `channel` is `"email"`, `"sms"`, or `"push"` -- the three shapes the
/// prompt file documents as identical apart from the name.
fn provider_config_block(channel: &str, db: &str) -> String {
    let mut chars = channel.chars();
    let pascal = match chars.next() {
        Some(f) => f.to_uppercase().collect::<String>() + chars.as_str(),
        None => String::new(),
    };
    let struct_name = format!("{pascal}ProviderConfig");
    let table = format!("{channel}_provider_config");
    format!(
        r#"
struct {struct_name} {{
    id: i64,
    active: bool,
    host: str,
    port: i64,
    path: str,
    api_key: str,
    from_address: str,
}}

fn list_{table}() -> Result(json, Text) requires(role: "admin") {{
    return match db_connect("{db}") {{
        Ok(conn) => match db_query(conn, "SELECT id, active, host, port, path, api_key, from_address FROM {table} ORDER BY id") {{
            Ok(rows) => Ok(rows),
            Err(e) => Err(Text(e)),
        }},
        Err(e) => Err(Text(e)),
    }}
}}

fn create_{table}(c: {struct_name}) -> Result(i64, Text) requires(role: "admin") {{
    return match db_connect("{db}") {{
        Ok(conn) => match db_execute(conn, "INSERT INTO {table} (active, host, port, path, api_key, from_address) VALUES (?, ?, ?, ?, ?, ?)", c.active, c.host, c.port, c.path, c.api_key, c.from_address) {{
            Ok(n) => Ok(n),
            Err(e) => Err(Text(e)),
        }},
        Err(e) => Err(Text(e)),
    }}
}}

fn update_{table}(c: {struct_name}) -> Result(i64, Text) requires(role: "admin") {{
    return match db_connect("{db}") {{
        Ok(conn) => match db_execute(conn, "UPDATE {table} SET active = ?, host = ?, port = ?, path = ?, api_key = ?, from_address = ? WHERE id = ?", c.active, c.host, c.port, c.path, c.api_key, c.from_address, c.id) {{
            Ok(n) => Ok(n),
            Err(e) => Err(Text(e)),
        }},
        Err(e) => Err(Text(e)),
    }}
}}

fn delete_{table}(id: i64) -> Result(i64, Text) requires(role: "admin") {{
    return match db_connect("{db}") {{
        Ok(conn) => match db_execute(conn, "DELETE FROM {table} WHERE id = ?", id) {{
            Ok(n) => Ok(n),
            Err(e) => Err(Text(e)),
        }},
        Err(e) => Err(Text(e)),
    }}
}}
"#
    )
}

fn role_mapping_block(db: &str) -> String {
    format!(
        r#"
struct RoleMapping {{
    id: i64,
    app_role: str,
    idp_role: str,
}}

fn list_role_mapping() -> Result(json, Text) requires(role: "admin") {{
    return match db_connect("{db}") {{
        Ok(conn) => match db_query(conn, "SELECT id, app_role, idp_role FROM role_mapping ORDER BY id") {{
            Ok(rows) => Ok(rows),
            Err(e) => Err(Text(e)),
        }},
        Err(e) => Err(Text(e)),
    }}
}}

fn create_role_mapping(m: RoleMapping) -> Result(i64, Text) requires(role: "admin") {{
    return match db_connect("{db}") {{
        Ok(conn) => match db_execute(conn, "INSERT INTO role_mapping (app_role, idp_role) VALUES (?, ?)", m.app_role, m.idp_role) {{
            Ok(n) => Ok(n),
            Err(e) => Err(Text(e)),
        }},
        Err(e) => Err(Text(e)),
    }}
}}

fn update_role_mapping(m: RoleMapping) -> Result(i64, Text) requires(role: "admin") {{
    return match db_connect("{db}") {{
        Ok(conn) => match db_execute(conn, "UPDATE role_mapping SET app_role = ?, idp_role = ? WHERE id = ?", m.app_role, m.idp_role, m.id) {{
            Ok(n) => Ok(n),
            Err(e) => Err(Text(e)),
        }},
        Err(e) => Err(Text(e)),
    }}
}}

fn delete_role_mapping(id: i64) -> Result(i64, Text) requires(role: "admin") {{
    return match db_connect("{db}") {{
        Ok(conn) => match db_execute(conn, "DELETE FROM role_mapping WHERE id = ?", id) {{
            Ok(n) => Ok(n),
            Err(e) => Err(Text(e)),
        }},
        Err(e) => Err(Text(e)),
    }}
}}
"#
    )
}

/// `run.sh` contents -- `main.rs::cmd_init` writes this with the exec bit
/// set (a plain `fs::write` doesn't set it).
pub fn render_launcher_unix(project_name: &str) -> String {
    format!(
        r#"#!/bin/sh
# Starts {project_name}'s server: `nirdosha serve`, exposing the UI at
# GET / and the API at POST /api/<fn>.
#
# --jwks-file/--issuer/--audience below are placeholders (jwks.json holds
# an empty key set) -- the server starts and non-gated routes work as-is,
# but every `requires(role: ...)` route 401s until you replace them with
# a real identity provider's values. Delete all three flags entirely to
# run with no auth configured instead.
cd "$(dirname "$0")"
./nirdosha serve {project_name}.nir \
  --host 127.0.0.1 --port 8080 \
  --jwks-file jwks.json --issuer https://REPLACE_ME_ISSUER --audience REPLACE_ME_AUDIENCE \
  --db {project_name}.db
"#
    )
}

/// `run.bat` contents -- the Windows counterpart to `render_launcher_unix`.
pub fn render_launcher_windows(project_name: &str) -> String {
    format!(
        r#"@echo off
rem Starts {project_name}'s server: `nirdosha serve`, exposing the UI at
rem GET / and the API at POST /api/<fn>.
rem
rem --jwks-file/--issuer/--audience below are placeholders (jwks.json
rem holds an empty key set) -- the server starts and non-gated routes
rem work as-is, but every `requires(role: ...)` route 401s until you
rem replace them with a real identity provider's values. Delete all
rem three flags entirely to run with no auth configured instead.
cd /d "%~dp0"
nirdosha.exe serve {project_name}.nir --host 127.0.0.1 --port 8080 --jwks-file jwks.json --issuer https://REPLACE_ME_ISSUER --audience REPLACE_ME_AUDIENCE --db {project_name}.db
"#
    )
}

/// `jwks.json` contents -- an empty, syntactically valid key set so
/// `serve`'s `--jwks-file` starts successfully with no manual setup;
/// every `requires(role: ...)` route still honestly 401s (no key can
/// ever validate a token) until it's replaced with real IdP keys.
pub fn placeholder_jwks() -> &'static str {
    "{\"keys\": []}\n"
}
