//! The compiled-path plugin ABI. The interpreter-targeted half of this
//! module (`PluginBuiltin`/`PluginFn`/`NirdoshaPlugin`, which dispatched
//! into `Interpreter::plugins`) was removed along with the interpreter
//! itself — see git history for that shape if it's ever needed again.
//! Only `NativePluginBuiltin` survives: it never depended on the
//! interpreter's `Value`/`RuntimeError` types in the first place, since
//! it exists specifically to be called from *compiled* `.nir` code.

use crate::ast::Ty;

/// rfcs/0005-plugin-boundary-safety-and-performance.md §3: the
/// compiled-path answer `docs/ECOSYSTEM.md` names as a real, deliberate
/// gap ("no stable calling convention from generated LLVM IR into an
/// opaque `Arc<dyn Fn>` exists"). `PluginFn`'s own shape is exactly
/// right for the interpreter and exactly wrong for `codegen.rs` — a
/// Rust trait object has no meaning to LLVM IR generated by a
/// *different* compilation. This is the other half: a plugin that
/// *also* exports a plain, `#[no_mangle] extern "C"` symbol with a
/// scalar-only signature can be called directly from compiled `.nir`
/// code, exactly the way `codegen.rs`'s own `nir_det`/`nir_rank`/
/// `nir_str_eq` (Phase 5's "linked native call into a staticlib"
/// pattern, `emit_llvm_ir`'s preamble) already work — this generalizes
/// that mechanism to a third-party-provided symbol/library instead of
/// only `runtime-kernels/src/lib.rs`'s own.
///
/// Deliberately **not** a field on `PluginBuiltin` (which stays exactly
/// as it was): a native-callable builtin is a *stricter* subset (no
/// `str`/aggregate/`Db`/`Handle` — anything `codegen.rs::llvm_ty`
/// doesn't already emit a scalar LLVM type for, checked by
/// [`NativePluginBuiltin::validate`]), and keeping it a separate,
/// explicit opt-in avoids ever silently expecting a `str`-taking plugin
/// builtin to somehow compile.
pub struct NativePluginBuiltin {
    /// Must equal the corresponding `PluginBuiltin.name` this native
    /// form backs, and must also be the exact `#[no_mangle] extern "C"`
    /// symbol name in `static_lib` — `codegen.rs` emits one `declare`
    /// and one `call`, both spelled with this one name, the same way a
    /// user `fn`'s own name already doubles as its LLVM symbol.
    pub name: String,
    pub params: Vec<Ty>,
    pub ret: Ty,
    /// A precompiled `staticlib` (`.a`) containing `name`'s
    /// `#[no_mangle] extern "C"` definition — a plugin crate's own
    /// `include_bytes!(concat!(env!("OUT_DIR"), "/lib....a"))`, the
    /// exact pattern `codegen.rs`'s own `RUNTIME_KERNELS_LIB` already
    /// uses for its hand-written kernels. Linked into the final `clang`
    /// invocation alongside the generated `.ll` — see
    /// `codegen::build_with_native_plugins`.
    pub static_lib: &'static [u8],
}

impl NativePluginBuiltin {
    /// Every param and the return type must be a type `codegen.rs`
    /// already emits as a plain LLVM scalar (or `void`) — `str`,
    /// `Vector`/`Matrix`, `Json`, `Db`/`Mq`/`Handle`, any `Ty::Named`
    /// struct/enum, are all real ABI questions (multi-word values,
    /// pointers with real ownership) this narrow mechanism doesn't
    /// attempt to answer; see rfcs/0005 §3's own "harder, still-open
    /// question" for why that's a separate, bigger design, not an
    /// oversight here.
    pub fn validate(&self) -> Result<(), String> {
        fn is_native_scalar(ty: &Ty) -> bool {
            matches!(
                ty,
                Ty::I8 | Ty::I16 | Ty::I32 | Ty::I64 | Ty::U8 | Ty::U16 | Ty::U32 | Ty::U64 | Ty::Usize | Ty::F64 | Ty::Bool | Ty::Unit
            )
        }
        for p in &self.params {
            if !is_native_scalar(p) {
                return Err(format!(
                    "native plugin builtin `{}`: parameter type `{}` isn't a supported native-ABI \
                     scalar (only i8..usize/f64/bool are) -- str/aggregate/Db/Mq/Handle types can't \
                     cross this boundary yet (rfcs/0005 §3)",
                    self.name,
                    p.name()
                ));
            }
        }
        if !is_native_scalar(&self.ret) {
            return Err(format!(
                "native plugin builtin `{}`: return type `{}` isn't a supported native-ABI scalar",
                self.name,
                self.ret.name()
            ));
        }
        Ok(())
    }
}
