//! The compiled-path plugin ABI. The interpreter-targeted half of this
//! module (`PluginBuiltin`/`PluginFn`/`NirdoshaPlugin`, which dispatched
//! into `Interpreter::plugins`) was removed along with the interpreter
//! itself — see git history for that shape if it's ever needed again.
//! Only `NativePluginBuiltin` survives: it never depended on the
//! interpreter's `Value`/`RuntimeError` types in the first place, since
//! it exists specifically to be called from *compiled* `.nir` code.

use crate::ast::Ty;

/// rfcs/0005-plugin-boundary-safety-and-performance.md §3: the
/// compiled-path answer `docs/ECOSYSTEM.md` names as a real, deliberate
/// gap ("no stable calling convention from generated LLVM IR into an
/// opaque `Arc<dyn Fn>` exists"). `PluginFn`'s own shape is exactly
/// right for the interpreter and exactly wrong for `codegen.rs` — a
/// Rust trait object has no meaning to LLVM IR generated by a
/// *different* compilation. This is the other half: a plugin that
/// *also* exports a plain, `#[no_mangle] extern "C"` symbol with a
/// scalar-only signature can be called directly from compiled `.nir`
/// code, exactly the way `codegen.rs`'s own `nir_det`/`nir_rank`/
/// `nir_str_eq` (Phase 5's "linked native call into a staticlib"
/// pattern, `emit_llvm_ir`'s preamble) already work — this generalizes
/// that mechanism to a third-party-provided symbol/library instead of
/// only `runtime-kernels/src/lib.rs`'s own.
///
/// Deliberately **not** a field on `PluginBuiltin` (which stays exactly
/// as it was): a native-callable builtin is a *stricter* subset (no
/// `Vector`/`Matrix`/`Db`/`Mq`/`Json`/`Ty::Named` — anything
/// `codegen.rs::llvm_ty` doesn't already emit a plain-value LLVM type
/// for, checked by [`NativePluginBuiltin::validate`]), and keeping it a
/// separate, explicit opt-in avoids ever silently expecting an
/// aggregate-taking plugin builtin to somehow compile.
///
/// rfcs/0008-native-plugin-abi-widening.md Phase 1: `str` and `handle`
/// are *not* in that stricter subset — both already have a plain-value
/// LLVM representation `codegen.rs::llvm_ty` emits for every ordinary
/// `.nir` function today (`Ty::Str => "{ptr, i64}"`, passed/returned by
/// value in registers exactly like `f64`/`Dec128Bits`, never through
/// the `Vector`/`Matrix` sret/pointer convention; `Ty::Handle(_)` is a
/// plain opaque `i64`, its only safety coming from `ownership.rs`'s
/// affine tracking at the *type* level, same as `Ty::Thread`/
/// `Ty::Channel`/`Ty::File`). `Codegen::call`'s generic `sigs`-driven
/// dispatch (`codegen.rs:3952`) already handles both shapes correctly
/// for a `declare`d native symbol with zero special-casing — the only
/// thing that stopped a `str`/`handle`-typed native plugin from
/// compiling was this validator's own scalar-only restriction, not a
/// missing codegen capability.
///
/// `&handle(Kind)` (`Ty::Ref(Box::new(Ty::Handle(_)))`) is also accepted
/// — deliberately narrower than "any `Ty::Ref`" — for the same reason
/// the deleted interpreter-path `widget_query` test case needed it: a
/// *read* of a stateful resource must **borrow**, not consume, or a
/// handle could only ever be used once before its own `close` (rfcs/
/// 0005 §1's affine guarantee would make every real "connect, query N
/// times, close" plugin uncallable). `codegen.rs::llvm_ty` already
/// renders any `Ty::Ref(_)` as a plain one-word `ptr` — the *address* of
/// the underlying `i64` handle slot, not the handle value itself — so a
/// native plugin function taking `&handle(Kind)` must dereference that
/// pointer once to read the `i64` id (see `crates/plugin-example-
/// native-kv`'s `kv_get`/`kv_set` for a real, working example of both
/// the `.nir`-side `&h` call and the Rust-side `*const i64` deref).
pub struct NativePluginBuiltin {
    /// Must equal the corresponding `PluginBuiltin.name` this native
    /// form backs, and must also be the exact `#[no_mangle] extern "C"`
    /// symbol name in `static_lib` — `codegen.rs` emits one `declare`
    /// and one `call`, both spelled with this one name, the same way a
    /// user `fn`'s own name already doubles as its LLVM symbol.
    pub name: String,
    pub params: Vec<Ty>,
    pub ret: Ty,
    /// A precompiled `staticlib` (`.a`) containing `name`'s
    /// `#[no_mangle] extern "C"` definition — a plugin crate's own
    /// `include_bytes!(concat!(env!("OUT_DIR"), "/lib....a"))`, the
    /// exact pattern `codegen.rs`'s own `RUNTIME_KERNELS_LIB` already
    /// uses for its hand-written kernels. Linked into the final `clang`
    /// invocation alongside the generated `.ll` — see
    /// `codegen::build_with_native_plugins`.
    pub static_lib: &'static [u8],
    /// rfcs/0011-uniform-service-provider-model.md §2/§5's
    /// convention-plus-override rule: a `<shape>_provider_<scheme>_connect`
    /// registration's admission ceiling is normally derived from its
    /// scheme (`NIRDOSHA_KERNEL_MAX_<SCHEME>`-shaped default), but a
    /// provider may pin its own env var name here instead. `None` for
    /// every non-provider native builtin (the vast majority — anything
    /// not named `..._connect`), and for a provider willing to accept the
    /// convention default.
    pub env_var: Option<&'static str>,
    /// Same convention-plus-override pairing as `env_var`, for the
    /// numeric ceiling itself (§5's `default_max`) rather than the env
    /// var that can override it at runtime. `None` means "use this
    /// registry's generic default," not "unlimited."
    pub default_max: Option<i64>,
}

impl NativePluginBuiltin {
    /// Every param and the return type must be a type `codegen.rs`
    /// already emits as a plain *value* (passed/returned in registers,
    /// never through the `sret`/by-pointer convention `Vector`/`Matrix`/
    /// `Ty::Named` need) — scalars, `str` (a `{ptr, i64}` two-word
    /// value), and `handle(Kind)` (a plain `i64`) all qualify.
    /// `Vector`/`Matrix`/`Json`/`Db`/`Mq`/any `Ty::Named` struct/enum do
    /// not: those are real ABI questions (variable-size aggregates,
    /// pointers with real ownership beyond a single opaque word) this
    /// narrow mechanism doesn't attempt to answer — see rfcs/0005 §3's
    /// own "harder, still-open question" for why that's separate,
    /// bigger design, not an oversight here.
    ///
    /// A `str` parameter crosses as the plugin author's own
    /// `#[repr(C)]` struct of `(ptr: *const u8, len: i64)` passed by
    /// value (matching `runtime-kernels/src/lib.rs`'s `Dec128Bits`
    /// pattern for its own two-word `{i64, i64}` values) — **not**
    /// NUL-terminated, `len` is load-bearing. A `str` return works the
    /// same way in reverse: the plugin allocates its own buffer (e.g.
    /// via `Box::leak`) and returns `(ptr, len)` by value; nothing on
    /// the Nirdosha side ever frees a plugin-returned string, the same
    /// permanent-leak posture `codegen.rs`'s own `sha256_hex` builtin
    /// already has for the identical reason (`Ty::Str` isn't affine, so
    /// there's no scope-closing point to hook a free onto) — see
    /// `crates/plugin-example-native-shout` for a real, working example
    /// of both directions.
    pub fn validate(&self) -> Result<(), String> {
        fn is_native_value(ty: &Ty) -> bool {
            matches!(
                ty,
                Ty::I8
                    | Ty::I16
                    | Ty::I32
                    | Ty::I64
                    | Ty::U8
                    | Ty::U16
                    | Ty::U32
                    | Ty::U64
                    | Ty::Usize
                    | Ty::F64
                    | Ty::Bool
                    | Ty::Unit
                    | Ty::Str
                    | Ty::Handle(_)
            ) || matches!(ty, Ty::Ref(inner) if matches!(inner.as_ref(), Ty::Handle(_)))
        }
        for p in &self.params {
            if !is_native_value(p) {
                return Err(format!(
                    "native plugin builtin `{}`: parameter type `{}` isn't a supported native-ABI \
                     value (i8..usize/f64/bool/str/handle(..)/&handle(..) are) -- Vector/Matrix/Json/Db/Mq/struct \
                     types can't cross this boundary yet (rfcs/0005 §3, rfcs/0008 §Phase 1)",
                    self.name,
                    p.name()
                ));
            }
        }
        if !is_native_value(&self.ret) {
            return Err(format!(
                "native plugin builtin `{}`: return type `{}` isn't a supported native-ABI value",
                self.name,
                self.ret.name()
            ));
        }
        Ok(())
    }
}

/// rfcs/0011-uniform-service-provider-model.md §2, "Scheme → identifier
/// normalization, spelled out exactly": take the substring before
/// `://`, lowercase it, map `+`/`.`/`-` to `_`. `mysql+tls://...` →
/// `mysql_tls`; `POSTGRESQL://...` → `postgresql`. This exact function
/// is duplicated verbatim in `runtime-kernels` (§2's own "one function,
/// not two independent implementations that could drift" — there is no
/// shared crate between `compiler` and `runtime-kernels` to put a single
/// copy in), used there for the identical purpose: turning a runtime
/// `.nir` string into the same identifier this function computes at
/// build time from a plugin's declared scheme. Keep both copies in sync
/// by hand if this one ever changes.
pub fn normalize_scheme(scheme: &str) -> String {
    let bare = scheme.split("://").next().unwrap_or(scheme);
    bare.to_ascii_lowercase().chars().map(|c| if c == '+' || c == '.' || c == '-' { '_' } else { c }).collect()
}

/// Splits a native plugin builtin's name into `(shape, normalized_scheme)`
/// when it's a provider's `_connect` entry (`"db_provider_mysql_connect"`
/// -> `("db", "mysql")`), or `None` for any other native builtin (the
/// common case — an ordinary scalar-ABI function with no provider shape,
/// e.g. `plugin_shout`). Used by `codegen.rs`'s Phase 4 eager-registration
/// pass to derive `register_domain`'s `name`/`env_var` arguments per
/// rfcs/0011 §3 ("for a plugin provider, `<shape>_provider_<normalized_
/// scheme>`") and §2 ("`NIRDOSHA_KERNEL_MAX_<SHAPE>_<NORMALIZED_SCHEME>`
/// convention default"). Deliberately re-derives the same
/// `_provider_`/`_connect` parse `validate_plugin_roster` already does
/// rather than sharing state with it, since that function only returns
/// pass/fail, not the parsed pieces.
pub fn provider_shape_and_scheme(name: &str) -> Option<(&str, String)> {
    let connect_prefix = name.strip_suffix("_connect")?;
    let provider_at = connect_prefix.find("_provider_")?;
    let shape = &connect_prefix[..provider_at];
    let scheme_raw = &connect_prefix[provider_at + "_provider_".len()..];
    if scheme_raw.is_empty() {
        return None;
    }
    Some((shape, normalize_scheme(scheme_raw)))
}

/// rfcs/0011 §2: "Built-in scheme identifiers, pinned exactly rather
/// than left implicit (this is the set a plugin may *not* register)."
/// `sqlite` has no `://` to strip (a bare path or `:memory:` — a
/// fallback rule, not a normalized scheme) but is still a reserved
/// identifier a plugin scheme must not collide with.
pub const BUILTIN_SCHEME_IDENTIFIERS: &[&str] = &["sqlite", "postgres", "postgresql", "redis", "http", "https"];

/// rfcs/0011 §2: "A shape's plugin contract is four functions or none,
/// checked at build time" + the two scheme-collision rules. Operates on
/// the whole registered roster (unlike [`NativePluginBuiltin::validate`],
/// which only checks one builtin's own ABI shape) because both checks
/// here are inherently cross-plugin: whether a `_connect` function's
/// siblings exist, and whether two providers' normalized schemes
/// collide. Only names containing `_provider_` and ending in `_connect`
/// participate — every other native plugin builtin (the common case:
/// an ordinary scalar-ABI function with no provider shape at all, e.g.
/// `plugin_shout`) is untouched by this check.
pub fn validate_plugin_roster(plugins: &[NativePluginBuiltin]) -> Result<(), String> {
    let names: std::collections::HashSet<&str> = plugins.iter().map(|p| p.name.as_str()).collect();

    let mut seen_schemes: std::collections::HashMap<String, &str> = std::collections::HashMap::new();
    for name in plugins.iter().map(|p| p.name.as_str()) {
        let Some(connect_prefix) = name.strip_suffix("_connect") else { continue };
        let Some(provider_at) = connect_prefix.find("_provider_") else { continue };
        let scheme_raw = &connect_prefix[provider_at + "_provider_".len()..];
        if scheme_raw.is_empty() {
            continue;
        }
        let scheme = normalize_scheme(scheme_raw);

        if BUILTIN_SCHEME_IDENTIFIERS.contains(&scheme.as_str()) {
            return Err(format!(
                "native plugin provider `{name}`: scheme `{scheme}` collides with a built-in identifier \
                 ({BUILTIN_SCHEME_IDENTIFIERS:?}) -- a plugin may not register a built-in scheme (rfcs/0011 §2)"
            ));
        }
        if let Some(other) = seen_schemes.get(&scheme) {
            return Err(format!(
                "native plugin providers `{other}` and `{name}`: both normalize to scheme `{scheme}` -- \
                 two plugins may not register the same identifier (rfcs/0011 §2)"
            ));
        }
        seen_schemes.insert(scheme, name);

        // "Four functions or none": `_connect` requires `_is_valid`,
        // `_close`, and either `_op` (conn/stream shape) or `_request`
        // (call shape) — the shape isn't a separate declared field, it's
        // inferred from which sibling is present.
        let prefix = connect_prefix; // e.g. "db_provider_mysql"
        let has_op = names.contains(format!("{prefix}_op").as_str());
        let has_request = names.contains(format!("{prefix}_request").as_str());
        if !has_op && !has_request {
            return Err(format!(
                "native plugin provider `{name}`: registered `_connect` without a matching `{prefix}_op` \
                 (conn/stream shape) or `{prefix}_request` (call shape) -- a shape's plugin contract is four \
                 functions or none (rfcs/0011 §2)"
            ));
        }
        if !names.contains(format!("{prefix}_is_valid").as_str()) {
            return Err(format!(
                "native plugin provider `{name}`: registered `_connect` without a matching `{prefix}_is_valid` \
                 -- a shape's plugin contract is four functions or none (rfcs/0011 §2)"
            ));
        }
        if !names.contains(format!("{prefix}_close").as_str()) {
            return Err(format!(
                "native plugin provider `{name}`: registered `_connect` without a matching `{prefix}_close` \
                 -- a shape's plugin contract is four functions or none (rfcs/0011 §2)"
            ));
        }
    }
    Ok(())
}

#[cfg(test)]
mod tests {
    use super::*;

    fn provider(name: &str) -> NativePluginBuiltin {
        NativePluginBuiltin { name: name.to_string(), params: vec![Ty::Str], ret: Ty::I64, static_lib: &[], env_var: None, default_max: None }
    }

    #[test]
    fn normalize_scheme_matches_the_rfc_examples() {
        assert_eq!(normalize_scheme("mysql+tls://host"), "mysql_tls");
        assert_eq!(normalize_scheme("POSTGRESQL://host"), "postgresql");
        assert_eq!(normalize_scheme("s3.compat-v2://host"), "s3_compat_v2");
    }

    #[test]
    fn a_well_formed_four_function_conn_shape_set_passes() {
        let plugins = vec![
            provider("db_provider_fakescheme_connect"),
            provider("db_provider_fakescheme_op"),
            provider("db_provider_fakescheme_is_valid"),
            provider("db_provider_fakescheme_close"),
        ];
        validate_plugin_roster(&plugins).expect("a well-formed four-function set must validate");
    }

    #[test]
    fn a_well_formed_four_function_call_shape_set_passes() {
        let plugins = vec![
            provider("authedhttp_provider_authedhttp_connect"),
            provider("authedhttp_provider_authedhttp_request"),
            provider("authedhttp_provider_authedhttp_is_valid"),
            provider("authedhttp_provider_authedhttp_close"),
        ];
        validate_plugin_roster(&plugins).expect("a well-formed call-shape four-function set must validate");
    }

    #[test]
    fn a_connect_missing_close_fails_with_the_named_function() {
        let plugins = vec![
            provider("db_provider_fakescheme_connect"),
            provider("db_provider_fakescheme_op"),
            provider("db_provider_fakescheme_is_valid"),
        ];
        let err = validate_plugin_roster(&plugins).expect_err("a missing _close must fail");
        assert!(err.contains("db_provider_fakescheme_close"), "expected the missing function named, got: {err}");
    }

    #[test]
    fn two_plugins_normalizing_to_the_same_identifier_fail_with_the_named_collision() {
        let plugins = vec![
            provider("db_provider_mysql_connect"),
            provider("db_provider_mysql_op"),
            provider("db_provider_mysql_is_valid"),
            provider("db_provider_mysql_close"),
            provider("mq_provider_mysql_connect"),
            provider("mq_provider_mysql_op"),
            provider("mq_provider_mysql_is_valid"),
            provider("mq_provider_mysql_close"),
        ];
        let err = validate_plugin_roster(&plugins).expect_err("colliding normalized schemes must fail");
        assert!(err.contains("mysql"), "expected the colliding identifier named, got: {err}");
    }

    #[test]
    fn a_plugin_scheme_colliding_with_postgres_fails() {
        let plugins = vec![
            provider("db_provider_postgres_connect"),
            provider("db_provider_postgres_op"),
            provider("db_provider_postgres_is_valid"),
            provider("db_provider_postgres_close"),
        ];
        let err = validate_plugin_roster(&plugins).expect_err("a built-in scheme collision must fail");
        assert!(err.contains("postgres"), "expected the built-in identifier named, got: {err}");
    }

    #[test]
    fn non_provider_native_builtins_are_untouched_by_roster_validation() {
        let plugins = vec![provider("plugin_shout")];
        validate_plugin_roster(&plugins).expect("a plain native builtin with no _provider_..._connect shape must pass untouched");
    }
}
