apiVersion: v1
kind: Service
metadata:
  name: {{ include "nirdosha.fullname" . }}
  labels:
    {{- include "nirdosha.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  selector:
    {{- include "nirdosha.selectorLabels" . | nindent 4 }}
  ports:
    - name: http
      port: {{ .Values.service.port }}
      targetPort: http
    {{- if .Values.presence.enabled }}
    - name: presence
      port: {{ .Values.presence.gateway.port }}
      targetPort: presence
    {{- end }}
