//! A real, local AML-risk model signal -- the design note's "AI model
//! integration" section, honestly scoped:
//!
//! > "Allowed demo outputs: risk score, anomaly score, pattern
//! > classification, prioritization recommendation... The model must not
//! > directly perform: fraud.finding_record, case.close, risk.lower,
//! > restriction.remove, sar.submit."
//!
//! This crate already has a real ONNX driver available
//! (`nirdosha-scoring-model-onnx`, wrapping a real `ort::Session`) and a
//! real fraud-scoring fixture -- but that fixture's four trained features
//! (`velocity_1h`, `distinct_payees_7d`, `amount_dev_30d`,
//! `impossible_travel`) are not features this crate can honestly compute:
//! `TransactionEvent` carries no counterparty/geo data. Reusing that
//! fixture with fabricated inputs would be exactly the "aspirational, not
//! honest" scoring this workspace's other drivers avoid. Instead,
//! `tests/fixtures/ctms_velocity_signal_v1_test_fixture.onnx` is this
//! crate's own small, real ONNX graph (checked-in binary, generated by
//! `scripts/gen_ctms_onnx.py` -- see that script's own doc comment) over
//! exactly the two features `crate::rules::AlertCandidate` already
//! provides for real: `debit_count` and a normalized `debit_total_minor`.
//!
//! **Structural enforcement of "advisory only".** [`ModelSignal`] is never
//! consulted by [`crate::alert::CtmsAlertGatewayV1::create`]'s
//! authorization decision or by [`crate::alert::AlertStore::create_or_get`]'s
//! idempotency key -- the deterministic rule alone remains the
//! authoritative trigger. A caller may attach a `ModelSignal` to the
//! created `Alert` purely as advisory metadata; there is no code path from
//! a model score to creating, closing, or dispositioning anything.

use std::path::Path;

use nirdosha_scoring_model_onnx::{LoadError, Model, ModelRuntime, ModelSpec, OnnxRuntime, ScoreError, SignedArtifact};
use sha2::{Digest, Sha256};

use crate::rules::AlertCandidate;

/// RFC 0025 §8.3's "model receipt": exactly the fields the design note
/// requires be recorded for every model result, so a model output is
/// audit-traceable the same way a gateway decision is -- see
/// `crate::alert::ModelSignal`, which is this attached to an `Alert`.
#[derive(Debug, Clone, PartialEq)]
pub struct ModelReceipt {
    pub model_id: String,
    pub model_version: String,
    pub input_digest: String,
    pub output_digest: String,
    pub score: f64,
    pub explanation: Vec<String>,
    /// Always `false` for this deterministic reference model -- the field
    /// exists because the design note requires it be recorded, not because
    /// this model can actually go out-of-distribution.
    pub abstained: bool,
    pub limitations: Vec<String>,
    pub scored_at_ms: u64,
}

fn hex_encode(bytes: &[u8]) -> String {
    bytes.iter().map(|b| format!("{b:02x}")).collect()
}

fn decode_hex_digest(hex: &str) -> Option<[u8; 32]> {
    if hex.len() != 64 {
        return None;
    }
    let mut out = [0u8; 32];
    for (i, byte) in out.iter_mut().enumerate() {
        *byte = u8::from_str_radix(&hex[i * 2..i * 2 + 2], 16).ok()?;
    }
    Some(out)
}

/// Wraps the real ONNX driver for this crate's own honestly-scoped
/// features.
pub struct VelocitySignalModel {
    model: Box<dyn Model>,
    spec: ModelSpec,
}

impl VelocitySignalModel {
    pub fn load_from_fixture(onnx_path: impl AsRef<Path>, sha256_path: impl AsRef<Path>) -> Result<Self, LoadError> {
        let bytes = std::fs::read(onnx_path.as_ref()).map_err(|e| LoadError::Onnx(e.to_string()))?;
        let pinned = std::fs::read_to_string(sha256_path.as_ref()).map_err(|e| LoadError::Onnx(e.to_string()))?;
        let sha256 = decode_hex_digest(pinned.trim())
            .ok_or_else(|| LoadError::Onnx(format!("{} is not a valid 64-char hex sha256 digest", sha256_path.as_ref().display())))?;
        let spec = ModelSpec {
            name: "ctms_velocity_signal_v1".to_string(),
            version: "1".to_string(),
            inputs: vec!["debit_count_24h".to_string(), "debit_total_minor_24h_norm".to_string()],
            outputs: vec!["score".to_string()],
        };
        let artifact = SignedArtifact { spec: spec.clone(), bytes, sha256 };
        let model = OnnxRuntime.load(&artifact)?;
        Ok(Self { model, spec })
    }

    /// Scores an [`AlertCandidate`]'s own already-observed features (debit
    /// count and total over the rule's window) -- no fabricated inputs.
    /// The normalization divisor (1,000,000 minor units) matches
    /// `scripts/gen_ctms_onnx.py`'s own reference-weight scale.
    pub fn score_candidate(&self, candidate: &AlertCandidate, now_ms: u64) -> Result<ModelReceipt, ScoreError> {
        let features = [candidate.debit_count as f64, candidate.debit_total_minor as f64 / 1_000_000.0];
        let output = self.model.score(&features)?;

        let mut input_hasher = Sha256::new();
        for feature in features {
            input_hasher.update(feature.to_le_bytes());
        }
        let input_digest = hex_encode(&input_hasher.finalize());
        let output_digest = hex_encode(&Sha256::digest(output.score.to_le_bytes()));

        Ok(ModelReceipt {
            model_id: self.spec.name.clone(),
            model_version: self.spec.version.clone(),
            input_digest,
            output_digest,
            score: output.score,
            explanation: output.explanation,
            abstained: false,
            limitations: vec![
                "reference weights only, not a production AML model".to_string(),
                "scores only debit_count/debit_total_minor -- no counterparty, geo, or device signal".to_string(),
            ],
            scored_at_ms: now_ms,
        })
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use std::path::PathBuf;

    fn fixture_dir() -> PathBuf {
        Path::new(env!("CARGO_MANIFEST_DIR")).join("tests/fixtures")
    }

    fn model() -> VelocitySignalModel {
        let dir = fixture_dir();
        VelocitySignalModel::load_from_fixture(dir.join("ctms_velocity_signal_v1_test_fixture.onnx"), dir.join("ctms_velocity_signal_v1_test_fixture.onnx.sha256"))
            .expect("real fixture model must load")
    }

    fn candidate(debit_count: usize, debit_total_minor: u64) -> AlertCandidate {
        AlertCandidate {
            rule_id: "velocity_24h".to_string(),
            rule_version: 1,
            key: "cust-1".to_string(),
            window_start_ms: 0,
            window_end_ms: 1_000,
            severity: "high".to_string(),
            matched_event_ids: vec![],
            debit_count,
            debit_total_minor,
        }
    }

    #[test]
    fn scores_match_the_independently_computed_reference_values() {
        let model = model();
        // Independently computed in Python (numpy, not onnxruntime) by
        // scripts/gen_ctms_onnx.py itself, from the same weights/bias the
        // fixture embeds: sigmoid([5,1] . [0.6,0.9] + (-3.0)) = 0.7109495
        let receipt = model.score_candidate(&candidate(5, 1_000_000), 0).unwrap();
        assert!((receipt.score - 0.7109495).abs() < 0.0005, "got {}", receipt.score);
        assert!(!receipt.abstained);
        assert!(!receipt.limitations.is_empty());
    }

    #[test]
    fn a_bigger_velocity_scores_higher() {
        let model = model();
        let low = model.score_candidate(&candidate(5, 1_000_000), 0).unwrap();
        let high = model.score_candidate(&candidate(10, 3_000_000), 0).unwrap();
        assert!(high.score > low.score, "low={} high={}", low.score, high.score);
    }

    #[test]
    fn scoring_the_same_candidate_twice_yields_the_same_input_and_output_digest() {
        let model = model();
        let a = model.score_candidate(&candidate(5, 1_000_000), 0).unwrap();
        let b = model.score_candidate(&candidate(5, 1_000_000), 0).unwrap();
        assert_eq!(a.input_digest, b.input_digest);
        assert_eq!(a.output_digest, b.output_digest);
    }

    #[test]
    fn rejects_a_tampered_fixture_via_the_underlying_digest_check() {
        let dir = fixture_dir();
        let mut bytes = std::fs::read(dir.join("ctms_velocity_signal_v1_test_fixture.onnx")).unwrap();
        bytes.push(0);
        let tampered_path = std::env::temp_dir().join(format!("ctms_tampered_model_{}.onnx", std::process::id()));
        std::fs::write(&tampered_path, bytes).unwrap();
        let result = VelocitySignalModel::load_from_fixture(&tampered_path, dir.join("ctms_velocity_signal_v1_test_fixture.onnx.sha256"));
        assert!(matches!(result, Err(LoadError::IntegrityMismatch { .. })));
        let _ = std::fs::remove_file(&tampered_path);
    }
}
