//! `login! { .. }` — a declarative login screen for the Nirdosha Rust
//! dialect.
//!
//! Registers a cookie-based login route with `Router::with_login` and
//! generates the mount function expected by the v2 translation
//! contract (`mount: mount_<ScreenName>`).
//!
//! ```ignore
//! nirdosha_rt::login! {
//!     mount: mount_login,
//!     path: "/login",
//!     mode: demo,
//!     demo_users: [
//!         { username: "admin", password: "admin", roles: ["admin"] },
//!         { username: "user",  password: "user",  roles: ["user"] },
//!     ],
//!     landing: landing_path,
//! }
//! ```
//!
//! The optional `landing:` names a function `fn(&Auth) -> &'static str`
//! (typically generated by `nirdosha_rt::landing!` or `app_shell!`) that
//! picks where a successful login redirects. When omitted the redirect
//! target is `"/"`.
//!
//! `mode: demo` expands to a `verify` closure that matches the listed
//! demo users and returns their roles. This is fixture-grade and
//! disclosed as such — suitable for development, tests, and the
//! preview rail, not for production.
//!
//! `mode: production` expands to a `verify` closure that reads a user
//! list from the `NIRDOSHA_LOGIN_USERS` environment variable (a path
//! to a JSON file). If the variable is unset or the file cannot be
//! parsed, every login attempt is rejected and a single warning is
//! logged on first use. The JSON file format is:
//!
//! ```json
//! [
//!   {"username": "admin", "password": "...", "roles": ["admin"]}
//! ]
//! ```
//!
//! Production deployments that do not want plaintext passwords in a
//! JSON file should replace the generated macro invocation with a
//! custom `Router::with_login` call backed by their own identity
//! store; this macro supplies only the wiring and a documented
//! env-var hook.
//!
//! The generated `verify` closure accepts `&str` arguments; because it
//! is emitted by a proc macro and compiled by `rustc` (not the
//! Nirdosha `.nir` typechecker), it is exempt from the dialect's
//! user-fn `str` restriction.

use proc_macro::TokenStream;
use proc_macro2::TokenStream as TokenStream2;
use quote::quote;
use syn::bracketed;
use syn::parse::{Parse, ParseStream};
use syn::{Ident, LitStr, Token};

enum Mode {
    Demo,
    Production,
}

impl Parse for Mode {
    fn parse(input: ParseStream) -> syn::Result<Self> {
        let ident: Ident = input.parse()?;
        if ident == "demo" {
            Ok(Mode::Demo)
        } else if ident == "production" {
            Ok(Mode::Production)
        } else {
            Err(syn::Error::new(ident.span(), "expected `demo` or `production`"))
        }
    }
}

struct DemoUser {
    username: LitStr,
    password: LitStr,
    roles: Vec<LitStr>,
}

impl Parse for DemoUser {
    fn parse(input: ParseStream) -> syn::Result<Self> {
        let content;
        syn::braced!(content in input);
        let mut username = None;
        let mut password = None;
        let mut roles = Vec::new();
        while !content.is_empty() {
            let key: Ident = content.parse()?;
            content.parse::<Token![:]>()?;
            if key == "username" {
                username = Some(content.parse()?);
            } else if key == "password" {
                password = Some(content.parse()?);
            } else if key == "roles" {
                let list;
                bracketed!(list in content);
                while !list.is_empty() {
                    roles.push(list.parse()?);
                    if list.peek(Token![,]) {
                        list.parse::<Token![,]>()?;
                    }
                }
            } else {
                return Err(syn::Error::new(key.span(), "expected `username`, `password`, or `roles`"));
            }
            if content.peek(Token![,]) {
                content.parse::<Token![,]>()?;
            }
        }
        let username = username.ok_or_else(|| syn::Error::new(content.span(), "demo user needs `username`"))?;
        let password = password.ok_or_else(|| syn::Error::new(content.span(), "demo user needs `password`"))?;
        Ok(DemoUser { username, password, roles })
    }
}

struct LoginInput {
    mount: Ident,
    path: LitStr,
    mode: Mode,
    demo_users: Vec<DemoUser>,
    landing: Option<Ident>,
}

impl Parse for LoginInput {
    fn parse(input: ParseStream) -> syn::Result<Self> {
        let mut mount = None;
        let mut path = None;
        let mut mode = None;
        let mut demo_users = Vec::new();
        let mut landing = None;

        while !input.is_empty() {
            let key: Ident = input.parse()?;
            input.parse::<Token![:]>()?;
            if key == "mount" {
                mount = Some(input.parse()?);
            } else if key == "path" {
                path = Some(input.parse()?);
            } else if key == "mode" {
                mode = Some(input.parse()?);
            } else if key == "demo_users" {
                let list;
                bracketed!(list in input);
                while !list.is_empty() {
                    demo_users.push(list.parse()?);
                    if list.peek(Token![,]) {
                        list.parse::<Token![,]>()?;
                    }
                }
            } else if key == "landing" {
                landing = Some(input.parse()?);
            } else {
                return Err(syn::Error::new(key.span(), "expected `mount`, `path`, `mode`, `demo_users`, or `landing`"));
            }
            if input.peek(Token![,]) {
                input.parse::<Token![,]>()?;
            }
        }

        let mount = mount.ok_or_else(|| syn::Error::new(input.span(), "`mount:` is required"))?;
        let path = path.ok_or_else(|| syn::Error::new(input.span(), "`path:` is required"))?;
        let mode = mode.ok_or_else(|| syn::Error::new(input.span(), "`mode:` is required"))?;

        if matches!(mode, Mode::Demo) && demo_users.is_empty() {
            return Err(syn::Error::new(input.span(), "`mode: demo` requires at least one `demo_users` entry"));
        }
        if matches!(mode, Mode::Production) && !demo_users.is_empty() {
            return Err(syn::Error::new(input.span(), "`mode: production` does not use `demo_users`; set `NIRDOSHA_LOGIN_USERS` at runtime"));
        }

        Ok(LoginInput { mount, path, mode, demo_users, landing })
    }
}

pub fn expand(input: TokenStream) -> TokenStream {
    let parsed = match syn::parse::<LoginInput>(input) {
        Ok(p) => p,
        Err(e) => return e.to_compile_error().into(),
    };
    expand_parsed(parsed).into()
}

fn expand_parsed(input: LoginInput) -> TokenStream2 {
    let mount = &input.mount;
    let path = &input.path;

    let landing = match &input.landing {
        Some(l) => quote!(Some(#l)),
        None => quote!(None),
    };

    let verify = match input.mode {
        Mode::Demo => {
            let arms = input.demo_users.iter().map(|u| {
                let username = &u.username;
                let password = &u.password;
                let roles: Vec<_> = u.roles.iter().map(|r| quote!(#r.to_string())).collect();
                quote! {
                    (#username, #password) => Some(vec![#(#roles),*]),
                }
            });
            quote! {
                |username: &str, password: &str| -> Option<Vec<String>> {
                    match (username, password) {
                        #(#arms)*
                        _ => None,
                    }
                }
            }
        }
        Mode::Production => {
            quote! {
                |username: &str, password: &str| -> Option<Vec<String>> {
                    use ::std::sync::Once;
                    static WARN_ONCE: Once = Once::new();
                    let file_path = match ::std::env::var("NIRDOSHA_LOGIN_USERS") {
                        Ok(v) => v,
                        Err(_) => {
                            WARN_ONCE.call_once(|| {
                                eprintln!("login! mode=production: NIRDOSHA_LOGIN_USERS is unset; all login attempts will be rejected");
                            });
                            return None;
                        }
                    };
                    let contents = match ::std::fs::read_to_string(&file_path) {
                        Ok(c) => c,
                        Err(e) => {
                            WARN_ONCE.call_once(|| {
                                eprintln!("login! mode=production: failed to read {}: {}", file_path, e);
                            });
                            return None;
                        }
                    };
                    #[derive(::serde::Deserialize)]
                    struct LoginUser {
                        username: String,
                        password: String,
                        roles: Vec<String>,
                    }
                    let users: Vec<LoginUser> = match ::serde_json::from_str(&contents) {
                        Ok(u) => u,
                        Err(e) => {
                            WARN_ONCE.call_once(|| {
                                eprintln!("login! mode=production: failed to parse {}: {}", file_path, e);
                            });
                            return None;
                        }
                    };
                    users.into_iter().find_map(|u| {
                        if u.username == username && u.password == password {
                            Some(u.roles)
                        } else {
                            None
                        }
                    })
                }
            }
        }
    };

    quote! {
        /// Generated by `nirdosha_rt::login!` — see its own doc comment.
        #[allow(dead_code)]
        pub fn #mount(mut router: ::nirdosha_rt::Router) -> ::nirdosha_rt::Router {
            let landing: Option<fn(&::nirdosha_rt::Auth) -> &'static str> = #landing;
            router = match landing {
                Some(l) => router.with_login_landing(#path, #verify, l),
                None => router.with_login(#path, #verify),
            };
            router
        }
    }
}
