//! A minimal, dialect-native HTTP layer over `prelude::{listen, accept,
//! Tcp}`'s raw sockets: request parsing, `{param}`-templated routing,
//! and an OpenAPI 3.0 document generated by `Router::dispatch` itself
//! for every service — `GET /openapi.json` always exists, with no
//! opt-in step.
//!
//! **Road 1 / Road 2 (RFC 0020).** A gated route's actual enforcement
//! is `Auth::prove::<R>()`, called once per request inside
//! `Router::{get,post,put,delete}_gated`, using the exact `RoleProof<R>`
//! mechanism `role.rs` already makes unforgeable. The OpenAPI
//! document's role annotation is a *read* of that same `R::NAME` —
//! captured at route-registration time, not independently declared —
//! so it is a derived, non-authoritative projection by construction: it
//! cannot drift from what is actually enforced, because there is only
//! one source (`R`), not two.

use std::collections::HashMap;
use std::net::IpAddr;
use std::sync::{Arc, Mutex};

use crate::role::{Auth, Claim, ClaimProof, Role, RoleProof};

mod ratelimit;
#[cfg(feature = "dpop")]
mod dpop;
#[cfg(feature = "dpop")]
mod dpop_replay;
#[cfg(feature = "fleet-rate-limit")]
mod fleet_ratelimit;
#[cfg(feature = "tls")]
mod tls;

const SESSION_COOKIE: &str = "nirdosha_session";

/// Every session cookie this router mints carries all three — matching
/// `compiled-serve`'s own attribute set (the only prior art in this
/// codebase for a real session cookie): `HttpOnly` (unreachable from
/// page JS, irrelevant for the no-client-JS dialect but cheap and
/// correct anyway), `Secure` (never sent over a plain-HTTP connection),
/// and `SameSite=Strict` (never sent on a cross-site navigation or
/// request at all — this dialect's screens are same-origin `<form>`
/// posts, so `Strict` costs nothing real). `Secure` here assumes the
/// same disclosed deployment model `compiled-serve`'s own `ServeConfig`
/// doc comment states: this listener speaks plain HTTP itself; TLS, if
/// any, terminates at a deployer's own reverse proxy in front of it. A
/// browser talking to this process directly over plain HTTP would never
/// see this cookie sent back at all -- a real, disclosed limit of a
/// from-scratch HTTP/1.1 listener with no TLS of its own, not a bug.
const SESSION_COOKIE_ATTRS: &str = "HttpOnly; Secure; SameSite=Strict; Path=/";

/// A DPoP proof's own `iat` freshness window, and the matching window
/// `dpop_replay`'s cache remembers a `jti` for — one constant, so the
/// two stay in lockstep. RFC 9449 sets no mandated value; 300s is
/// generous enough for real network latency and clock drift while
/// still bounding how long a captured-off-the-wire proof stays
/// replayable at all.
#[cfg(feature = "dpop")]
const DPOP_PROOF_FRESHNESS_WINDOW_SECS: i64 = 300;

#[derive(Debug, Clone)]
pub struct Request {
    pub method: String,
    pub path: String,
    pub headers: HashMap<String, String>,
    pub body: String,
}

impl Request {
    pub fn header(&self, name: &str) -> Option<&str> {
        self.headers.get(&name.to_ascii_lowercase()).map(String::as_str)
    }

    /// Parse a raw HTTP/1.1 request exactly as `Tcp::recv()` hands it
    /// back: request line, headers, a blank line, then the body.
    pub fn parse(raw: &str) -> Option<Request> {
        let mut lines = raw.split("\r\n");
        let request_line = lines.next()?;
        let mut parts = request_line.split(' ');
        let method = parts.next()?.to_string();
        let path = parts.next()?.to_string();

        let mut headers = HashMap::new();
        let mut in_body = false;
        let mut body_lines = Vec::new();
        for line in lines {
            if in_body {
                body_lines.push(line);
                continue;
            }
            if line.is_empty() {
                in_body = true;
                continue;
            }
            if let Some((k, v)) = line.split_once(':') {
                headers.insert(k.trim().to_ascii_lowercase(), v.trim().to_string());
            }
        }
        Some(Request {
            method,
            path,
            headers,
            body: body_lines.join("\r\n"),
        })
    }

    fn path_without_query(&self) -> &str {
        self.path.split('?').next().unwrap_or(&self.path)
    }

    /// One cookie's value from the `Cookie` header (`a=1; b=2`).
    pub fn cookie(&self, name: &str) -> Option<String> {
        let raw = self.header("cookie")?;
        raw.split(';').find_map(|part| {
            let (k, v) = part.trim().split_once('=')?;
            (k == name).then(|| v.to_string())
        })
    }

    /// The parsed query string (`?a=1&b=2` → `{"a":"1","b":"2"}`).
    pub fn query(&self) -> HashMap<String, String> {
        match self.path.split_once('?') {
            Some((_, q)) => parse_urlencoded(q),
            None => HashMap::new(),
        }
    }

    /// The request body as key→value strings, regardless of whether it
    /// arrived as `application/json` (an API caller) or
    /// `application/x-www-form-urlencoded` (an ordinary HTML `<form>`
    /// POST — this dialect has no client-side JS, so every screen's
    /// form submits the plain browser default). One body shape, one
    /// parser either way — screens and the JSON API share the exact
    /// same create/update functions.
    pub fn form_or_json(&self) -> HashMap<String, String> {
        match self.header("content-type") {
            Some(ct) if ct.starts_with("application/json") => serde_json::from_str::<serde_json::Value>(&self.body)
                .ok()
                .and_then(|v| v.as_object().cloned())
                .map(|obj| obj.into_iter().map(|(k, v)| (k, json_scalar_to_string(&v))).collect())
                .unwrap_or_default(),
            _ => parse_urlencoded(&self.body),
        }
    }
}

fn json_scalar_to_string(v: &serde_json::Value) -> String {
    match v {
        serde_json::Value::String(s) => s.clone(),
        serde_json::Value::Null => String::new(),
        other => other.to_string(),
    }
}

fn parse_urlencoded(s: &str) -> HashMap<String, String> {
    s.split('&')
        .filter(|p| !p.is_empty())
        .filter_map(|pair| {
            let (k, v) = pair.split_once('=').unwrap_or((pair, ""));
            Some((url_decode(k), url_decode(v)))
        })
        .collect()
}

/// Percent-decodes into bytes first, then interprets as UTF-8 — naive
/// char-by-char decoding would corrupt any multi-byte percent-encoded
/// sequence (e.g. `%C3%A9`).
fn url_decode(s: &str) -> String {
    let mut bytes = Vec::new();
    let mut chars = s.chars();
    while let Some(c) = chars.next() {
        match c {
            '+' => bytes.push(b' '),
            '%' => {
                let hex: String = chars.by_ref().take(2).collect();
                match u8::from_str_radix(&hex, 16) {
                    Ok(byte) => bytes.push(byte),
                    Err(_) => bytes.extend_from_slice(hex.as_bytes()),
                }
            }
            c => {
                let mut buf = [0u8; 4];
                bytes.extend_from_slice(c.encode_utf8(&mut buf).as_bytes());
            }
        }
    }
    String::from_utf8_lossy(&bytes).into_owned()
}

/// An `Origin` header's own `(scheme, host, port)`, with the scheme's
/// real default port filled in when the origin carries none — so
/// `https://example.com` and `https://example.com:443` compare equal,
/// the same normalization `compiled-serve`'s own `parse_origin` already
/// does. `None` only when there's no `scheme://` separator at all.
fn parse_origin(origin: &str) -> Option<(&str, &str, u16)> {
    let (scheme, rest) = origin.split_once("://")?;
    let default_port = match scheme {
        "https" => 443,
        "http" => 80,
        _ => 0,
    };
    match rest.rsplit_once(':') {
        Some((host, port_str)) => match port_str.parse::<u16>() {
            Ok(port) => Some((scheme, host, port)),
            Err(_) => Some((scheme, rest, default_port)),
        },
        None => Some((scheme, rest, default_port)),
    }
}

fn origins_match(a: &str, b: &str) -> bool {
    match (parse_origin(a), parse_origin(b)) {
        (Some(pa), Some(pb)) => pa == pb,
        _ => a == b,
    }
}

/// Escapes `&`, `<`, `>`, `"`, `'` for safe interpolation into HTML —
/// every screen renderer routes user/entity data through this before
/// writing it into a page; nothing here ever trusts stored data to be
/// pre-sanitized.
pub fn html_escape(s: &str) -> String {
    s.replace('&', "&amp;")
        .replace('<', "&lt;")
        .replace('>', "&gt;")
        .replace('"', "&quot;")
        .replace('\'', "&#39;")
}

/// The one shared page template every server-rendered screen (and
/// `dashboard!`) wraps its body in — no client-side JS, no build step,
/// just enough CSS to make tables/forms/widgets legible.
pub fn page_shell(title: &str, extra_head: &str, body: &str) -> String {
    crate::theme::themed_page_shell_ex(title, "", extra_head, body)
}

#[derive(Debug, Clone)]
pub struct Response {
    pub status: u16,
    pub content_type: &'static str,
    pub body: String,
    pub extra_headers: Vec<(String, String)>,
}

impl Response {
    pub fn json(status: u16, value: &serde_json::Value) -> Response {
        Response {
            status,
            content_type: "application/json",
            body: value.to_string(),
            extra_headers: Vec::new(),
        }
    }

    pub fn text(status: u16, body: impl Into<String>) -> Response {
        Response {
            status,
            content_type: "text/plain",
            body: body.into(),
            extra_headers: Vec::new(),
        }
    }

    pub fn html(status: u16, body: impl Into<String>) -> Response {
        Response {
            status,
            content_type: "text/html; charset=utf-8",
            body: body.into(),
            extra_headers: Vec::new(),
        }
    }

    pub fn csv(status: u16, body: impl Into<String>) -> Response {
        Response {
            status,
            content_type: "text/csv; charset=utf-8",
            body: body.into(),
            extra_headers: Vec::new(),
        }
    }

    /// Serves the dialect's client-side-interactivity foundation: one
    /// small, hand-written, reviewable vanilla-JS asset (no bundler, no
    /// framework) — currently just `kanban_board!`'s drag-and-drop,
    /// calling back into the app's own already-gated JSON routes via
    /// `fetch()`. There is no client-side JS anywhere else in the
    /// dialect's generated output.
    pub fn javascript(status: u16, body: impl Into<String>) -> Response {
        Response {
            status,
            content_type: "text/javascript; charset=utf-8",
            body: body.into(),
            extra_headers: Vec::new(),
        }
    }

    pub fn no_content() -> Response {
        Response {
            status: 204,
            content_type: "text/plain",
            body: String::new(),
            extra_headers: Vec::new(),
        }
    }

    pub fn not_found() -> Response {
        Response::text(404, "not found")
    }

    pub fn forbidden() -> Response {
        Response::text(403, "forbidden")
    }

    pub fn bad_request(msg: impl Into<String>) -> Response {
        Response::text(400, msg)
    }

    /// A 302 redirect — used by every screen's POST handler (create,
    /// update, delete) to send the browser to the resulting page
    /// instead of rendering a bare API response, since these are
    /// ordinary `<form>` submissions, not API calls.
    pub fn redirect(location: impl Into<String>) -> Response {
        Response {
            status: 302,
            content_type: "text/plain",
            body: String::new(),
            extra_headers: vec![("Location".to_string(), location.into())],
        }
    }

    /// The complete HTTP/1.1 response, head and body together, as one
    /// string — shared by both `serve_until`'s sync path (`write_to`,
    /// below) and its async path (`serve_until_async`'s own socket
    /// write), so the wire format has exactly one definition regardless
    /// of which transport a given `Router` runs under.
    fn wire_string(&self) -> String {
        let mut head = format!(
            "HTTP/1.1 {} {}\r\nContent-Type: {}\r\nContent-Length: {}\r\nConnection: close\r\n",
            self.status,
            reason_phrase(self.status),
            self.content_type,
            self.body.len(),
        );
        for (name, value) in &self.extra_headers {
            head.push_str(&format!("{name}: {value}\r\n"));
        }
        head.push_str("\r\n");
        head.push_str(&self.body);
        head
    }

    fn write_to(&self, conn: &crate::prelude::Tcp) {
        conn.send(&self.wire_string());
    }
}

fn login_page_html(action: &str, error: Option<&str>) -> String {
    let error_html = match error {
        Some(msg) => format!("<p class=\"errors\">{}</p>", html_escape(msg)),
        None => String::new(),
    };
    page_shell(
        "Log in",
        "",
        &format!(
            "{error_html}<form method=\"post\" action=\"{action}\">\
             <p><label>Username</label><input type=\"text\" name=\"username\"></p>\
             <p><label>Password</label><input type=\"password\" name=\"password\"></p>\
             <p><button type=\"submit\">Log in</button></p>\
             </form>"
        ),
    )
}

fn reason_phrase(status: u16) -> &'static str {
    match status {
        200 => "OK",
        201 => "Created",
        204 => "No Content",
        302 => "Found",
        400 => "Bad Request",
        401 => "Unauthorized",
        403 => "Forbidden",
        404 => "Not Found",
        405 => "Method Not Allowed",
        500 => "Internal Server Error",
        _ => "Unknown",
    }
}

#[derive(Debug, Clone, Default)]
pub struct PathParams(HashMap<String, String>);

impl PathParams {
    pub fn get(&self, key: &str) -> Option<&str> {
        self.0.get(key).map(String::as_str)
    }
}

#[derive(Debug, Clone)]
enum Segment {
    Literal(String),
    Param(String),
}

#[derive(Debug, Clone)]
struct PathTemplate {
    segments: Vec<Segment>,
}

fn split_path(path: &str) -> Vec<&str> {
    path.trim_matches('/').split('/').filter(|s| !s.is_empty()).collect()
}

impl PathTemplate {
    fn parse(template: &str) -> PathTemplate {
        let segments = split_path(template)
            .into_iter()
            .map(|s| match s.strip_prefix('{').and_then(|s| s.strip_suffix('}')) {
                Some(name) => Segment::Param(name.to_string()),
                None => Segment::Literal(s.to_string()),
            })
            .collect();
        PathTemplate { segments }
    }

    fn matches(&self, path: &str) -> Option<PathParams> {
        let actual = split_path(path);
        if actual.len() != self.segments.len() {
            return None;
        }
        let mut params = HashMap::new();
        for (seg, value) in self.segments.iter().zip(actual.iter()) {
            match seg {
                Segment::Literal(lit) => {
                    if lit != value {
                        return None;
                    }
                }
                Segment::Param(name) => {
                    params.insert(name.clone(), value.to_string());
                }
            }
        }
        Some(PathParams(params))
    }

    fn as_openapi_path(&self) -> String {
        let rendered: Vec<String> = self
            .segments
            .iter()
            .map(|s| match s {
                Segment::Literal(l) => l.clone(),
                Segment::Param(p) => format!("{{{p}}}"),
            })
            .collect();
        format!("/{}", rendered.join("/"))
    }
}

type Handler = Arc<dyn Fn(&Request, &PathParams) -> Response + Send + Sync>;

#[derive(Clone)]
struct Route {
    method: &'static str,
    template: PathTemplate,
    summary: &'static str,
    /// Road 2: a read of the `R::NAME` used for the *actual* gate at
    /// registration time. `None` for an ungated route. Never the other
    /// way around — nothing here can cause a route to be gated; it only
    /// documents a gate that already exists.
    required_role: Option<&'static str>,
    /// Same idea as `required_role`, for a claim-gated route
    /// (`get_gated_claim`/etc.) — `(C::NAME, C::VALUE)`, a read of the
    /// *actual* gate, never the other way around.
    required_claim: Option<(&'static str, &'static str)>,
    handler: Handler,
}

/// One top-bar/side-nav link — a plain label + href, rendered on every
/// HTML screen once `Router::with_nav` is set.
#[derive(Clone)]
pub struct NavLink {
    pub label: &'static str,
    pub href: &'static str,
}

/// `verify(username, password)` returning the session's roles on
/// success — the one thing an app supplies; everything else (the
/// login form, the session cookie, the logout route, the nav bar's
/// Login/Logout button) is handled by the router itself.
/// `landing` optionally picks the post-login redirect target from the
/// freshly minted session.
#[derive(Clone)]
struct LoginConfig {
    path: String,
    verify: Arc<dyn Fn(&str, &str) -> Option<Vec<String>> + Send + Sync>,
    landing: Option<Arc<dyn Fn(&Auth) -> &'static str + Send + Sync>>,
}

/// A request → `Response` router with OpenAPI baked into `dispatch`
/// itself. `authenticate` turns a request into a session (e.g. reading
/// an `Authorization` header via the app's own identity fixture) —
/// this crate has no opinion on token formats, only on what happens
/// once you have an `Auth`.
#[derive(Clone)]
pub struct Router {
    title: &'static str,
    version: &'static str,
    routes: Vec<Route>,
    authenticate: Arc<dyn Fn(&Request) -> Auth + Send + Sync>,
    nav: Vec<NavLink>,
    nav_builder: Option<Arc<dyn Fn(&Auth) -> Vec<NavLink> + Send + Sync>>,
    login: Option<LoginConfig>,
    /// session id → (username, roles). In-memory, shared by clones, lost
    /// on restart — matches this dialect's other fixture-grade stores
    /// (`product_store`-style `Mutex<HashMap<..>>`s), not a claim of
    /// production session durability.
    sessions: Arc<Mutex<HashMap<String, (String, Vec<String>)>>>,
    /// CORS: the exact origin(s) this router reflects back on a
    /// credentialed response. Empty (the default) means no CORS headers
    /// are ever emitted at all — same posture as `compiled-serve`'s own
    /// `ServeConfig::allowed_origins`, ported here since this router had
    /// no CORS handling whatsoever before this. Never a wildcard: a
    /// credentialed response (this router always sends one, since every
    /// gated route relies on the session cookie) reflecting `*` would
    /// let *any* origin ride an authenticated user's session — the
    /// wildcard is what the custom-header/explicit-origin split in the
    /// CORS spec exists to prevent.
    allowed_origins: Vec<String>,
    /// Fixed-window, per-peer-IP rate limiting for `paths` — `None`
    /// (the default) means no path is rate-limited at all. Only takes
    /// effect through `serve_until`'s real TCP accept loop, the one
    /// source of a real peer IP; `dispatch` called directly (this
    /// crate's own tests, or an app embedding `Router` in its own
    /// server loop) never rate-limits — the same disclosed,
    /// per-process-only scope `ratelimit::RateLimiter` (ported from
    /// `compiled-serve`'s own) already states for its *fleet-wide*
    /// limit; this is that same limit's *dispatch-path* counterpart,
    /// not silently assumed away either.
    rate_limit: Option<RateLimitRule>,
    /// A Redis-backed sibling to `rate_limit`, for a multi-instance
    /// deployment — see `Router::with_fleet_rate_limit`'s own doc
    /// comment. `None` (the default) means no path is fleet-rate-limited.
    #[cfg(feature = "fleet-rate-limit")]
    fleet_rate_limit: Option<FleetRateLimitRule>,
    /// Which `serve_until` accept-loop implementation this router runs
    /// under — see [`Runtime`]'s own doc comment. `Runtime::default()`
    /// (`Async`) unless overridden by `with_runtime`.
    runtime: Runtime,
    /// `true` once `with_sender_constrained_tokens` is called — see
    /// [`check_dpop`](Router::check_dpop)'s own doc comment for the
    /// full enforcement this turns on.
    #[cfg(feature = "dpop")]
    require_dpop: bool,
    #[cfg(feature = "dpop")]
    dpop_replay: Arc<dpop_replay::DpopReplayCache>,
    /// `Some` once `ServeConfig`-level TLS is configured via
    /// `Router::with_tls` — see `tls.rs`'s own doc comment.
    #[cfg(feature = "tls")]
    tls: Option<Arc<tls::TlsConfig>>,
}

/// `serve_until`'s transport strategy — never changes what a route
/// handler looks like (still an ordinary sync `Fn(&Request,
/// &PathParams) -> Response`, on both variants) or what the dialect's
/// own driver accepts (`async fn` stays rejected there regardless of
/// this setting) — only how the accept loop underneath handlers is
/// implemented.
#[derive(Clone, Copy, Debug, PartialEq, Eq)]
pub enum Runtime {
    /// A tokio-based accept loop (`serve_until_async`): bounded worker
    /// *tasks*, not one OS thread per connection, with each handler
    /// invocation run via `tokio::task::spawn_blocking` (handlers can
    /// legitimately block — `communication_feed!`'s long-poll wait is
    /// exactly that shape — so this still never stalls the async
    /// reactor's own worker threads). The default: most apps this
    /// dialect targets are I/O-bound (waiting on a database, an
    /// upstream HTTP call, a long-poll), which is exactly where an
    /// async accept loop's lower per-connection overhead pays for
    /// itself; a CPU-bound app gets no benefit from this over `Sync`
    /// either way; requires this crate's `async-runtime` feature
    /// (on by default — see that feature's own `Cargo.toml` comment).
    Async,
    /// Today's original accept loop (`serve_until_sync`): one OS thread
    /// per accepted connection, bounded by `ServeConfig::max_connections`.
    /// Simple, no tokio dependency needed at all, and perfectly
    /// adequate for a low-concurrency app or one that's CPU-bound
    /// rather than I/O-bound (async buys nothing there).
    Sync,
}

/// Feature-aware: `Async` when `async-runtime` was actually compiled
/// in (the default, real feature set), `Sync` otherwise. `Router::new`
/// picking a default that then panics at `serve_until` time on a
/// `--no-default-features` build would defeat the entire point of that
/// build option -- skipping tokio for a build with no use for it should
/// mean "this router just uses the always-available transport
/// instead," not "this router silently carries a landmine until
/// someone calls `serve_until`."
#[cfg(feature = "async-runtime")]
impl Default for Runtime {
    fn default() -> Self {
        Runtime::Async
    }
}

#[cfg(not(feature = "async-runtime"))]
impl Default for Runtime {
    fn default() -> Self {
        Runtime::Sync
    }
}

#[derive(Clone)]
struct RateLimitRule {
    paths: Vec<String>,
    max_per_window: u32,
    window: std::time::Duration,
    limiter: Arc<ratelimit::RateLimiter>,
}

#[cfg(feature = "fleet-rate-limit")]
#[derive(Clone)]
struct FleetRateLimitRule {
    paths: Vec<String>,
    max_per_window: u32,
    window: std::time::Duration,
    limiter: Arc<fleet_ratelimit::FleetRateLimiter>,
}

/// Bounds socket workers and socket I/O waits. Handler execution must itself
/// be bounded; shutdown drains in-flight handlers rather than interrupting them.
#[derive(Clone, Copy, Debug)]
pub struct ServeConfig {
    pub max_connections: std::num::NonZeroUsize,
    pub io_timeout: std::time::Duration,
}

impl Default for ServeConfig {
    fn default() -> Self {
        Self {
            max_connections: std::num::NonZeroUsize::new(64).unwrap(),
            io_timeout: std::time::Duration::from_secs(5),
        }
    }
}

/// Resolves a session cookie to an `Auth`, if the cookie names a
/// session this router actually minted. Shared by every gated route's
/// closure and by the nav bar's Login/Logout rendering, so both agree
/// on what "logged in" means.
fn session_auth(sessions: &Arc<Mutex<HashMap<String, (String, Vec<String>)>>>, req: &Request) -> Option<Auth> {
    let sid = req.cookie(SESSION_COOKIE)?;
    let (user, roles) = sessions.lock().unwrap().get(&sid)?.clone();
    let role_refs: Vec<&str> = roles.iter().map(String::as_str).collect();
    Some(Auth::login(user.clone(), &role_refs))
}

/// A demo-grade session id: unique and unguessable-by-accident, but
/// **not** cryptographically secure — no CSPRNG is used. Fine for this
/// dialect's fixture-grade session store; a real deployment needs a
/// real secure-random source here, the same honesty this crate applies
/// to `mock_issue_token`-style fixtures elsewhere.
fn generate_session_id() -> String {
    use std::sync::atomic::{AtomicU64, Ordering};
    static COUNTER: AtomicU64 = AtomicU64::new(0);
    let count = COUNTER.fetch_add(1, Ordering::Relaxed);
    let nanos = std::time::SystemTime::now().duration_since(std::time::UNIX_EPOCH).map(|d| d.as_nanos()).unwrap_or(0);
    format!("{nanos:x}-{count:x}-{:p}", &count)
}

macro_rules! ungated_method {
    ($name:ident, $method:literal) => {
        pub fn $name(
            mut self,
            path: &'static str,
            summary: &'static str,
            handler: impl Fn(&Request, &PathParams) -> Response + Send + Sync + 'static,
        ) -> Self {
            self.routes.push(Route {
                method: $method,
                template: PathTemplate::parse(path),
                summary,
                required_role: None,
                required_claim: None,
                handler: Arc::new(handler),
            });
            self
        }
    };
}

macro_rules! gated_method {
    ($name:ident, $method:literal) => {
        pub fn $name<R: Role + 'static>(
            mut self,
            path: &'static str,
            summary: &'static str,
            handler: impl Fn(&Request, &PathParams, &RoleProof<R>) -> Response + Send + Sync + 'static,
        ) -> Self {
            let authenticate = self.authenticate.clone();
            let sessions = self.sessions.clone();
            let wrapped = move |req: &Request, params: &PathParams| -> Response {
                let auth = session_auth(&sessions, req).unwrap_or_else(|| authenticate(req));
                match auth.prove::<R>() {
                    Ok(proof) => handler(req, params, &proof),
                    Err(_) => Response::forbidden(),
                }
            };
            self.routes.push(Route {
                method: $method,
                template: PathTemplate::parse(path),
                summary,
                required_role: Some(R::NAME),
                required_claim: None,
                handler: Arc::new(wrapped),
            });
            self
        }
    };
}

macro_rules! gated_claim_method {
    ($name:ident, $method:literal) => {
        pub fn $name<C: Claim + 'static>(
            mut self,
            path: &'static str,
            summary: &'static str,
            handler: impl Fn(&Request, &PathParams, &ClaimProof<C>) -> Response + Send + Sync + 'static,
        ) -> Self {
            let authenticate = self.authenticate.clone();
            let sessions = self.sessions.clone();
            let wrapped = move |req: &Request, params: &PathParams| -> Response {
                let auth = session_auth(&sessions, req).unwrap_or_else(|| authenticate(req));
                match auth.prove_claim::<C>() {
                    Ok(proof) => handler(req, params, &proof),
                    Err(_) => Response::forbidden(),
                }
            };
            self.routes.push(Route {
                method: $method,
                template: PathTemplate::parse(path),
                summary,
                required_role: None,
                required_claim: Some((C::NAME, C::VALUE)),
                handler: Arc::new(wrapped),
            });
            self
        }
    };
}

/// One TLS-or-plain async request/response cycle -- the async
/// transport's own version of `tls::handle_sync_connection`'s sync
/// one, generic over the actual stream type (`tokio::net::TcpStream`
/// directly, or `tokio_rustls::server::TlsStream<TcpStream>` once a
/// handshake has already completed) so `serve_until_async`'s accept
/// loop needs this logic written exactly once regardless of which one
/// a given connection turns out to be. Single-read semantics, matching
/// `serve_until_sync`'s own (and `crate::prelude::Tcp::recv`'s own doc
/// comment on why).
#[cfg(feature = "async-runtime")]
async fn serve_one_async<S>(mut stream: S, io_timeout: std::time::Duration, peer_ip: IpAddr, router: Arc<Router>)
where
    S: tokio::io::AsyncRead + tokio::io::AsyncWrite + Unpin,
{
    use tokio::io::{AsyncReadExt, AsyncWriteExt};
    let mut buf = [0u8; 65536];
    let n = match tokio::time::timeout(io_timeout, stream.read(&mut buf)).await {
        Ok(Ok(n)) if n > 0 => n,
        _ => return,
    };
    let raw = String::from_utf8_lossy(&buf[..n]).into_owned();
    let response = match Request::parse(&raw) {
        Some(req) => {
            let router = Arc::clone(&router);
            // The one handler call, off the reactor's own worker
            // threads -- see `serve_until_async`'s own doc comment for
            // why.
            match tokio::task::spawn_blocking(move || router.dispatch_from_peer(&req, Some(peer_ip))).await {
                Ok(response) => response,
                Err(_) => return, // the handler panicked -- close with no response, matching `serve_until_sync`'s own `catch_unwind`
            }
        }
        None => Response::bad_request("malformed request"),
    };
    let _ = tokio::time::timeout(io_timeout, stream.write_all(response.wire_string().as_bytes())).await;
}

impl Router {
    pub fn new(authenticate: impl Fn(&Request) -> Auth + Send + Sync + 'static) -> Router {
        Router {
            title: "Nirdosha service",
            version: "0.1.0",
            routes: Vec::new(),
            authenticate: Arc::new(authenticate),
            nav: Vec::new(),
            nav_builder: None,
            login: None,
            sessions: Arc::new(Mutex::new(HashMap::new())),
            allowed_origins: Vec::new(),
            rate_limit: None,
            #[cfg(feature = "fleet-rate-limit")]
            fleet_rate_limit: None,
            runtime: Runtime::default(),
            #[cfg(feature = "dpop")]
            require_dpop: false,
            #[cfg(feature = "dpop")]
            dpop_replay: Arc::new(dpop_replay::DpopReplayCache::new()),
            #[cfg(feature = "tls")]
            tls: None,
        }
    }

    pub fn with_info(mut self, title: &'static str, version: &'static str) -> Self {
        self.title = title;
        self.version = version;
        self
    }

    /// A top-bar shown on every HTML screen, with a Login/Logout button
    /// on the right when `with_login` is also set.
    pub fn with_nav(mut self, links: Vec<NavLink>) -> Self {
        self.nav = links;
        self
    }

    /// Same nav bar as `with_nav`, but recomputed per request from the
    /// current authenticated session. Use this when menu items should
    /// appear or disappear based on the user's roles or claims.
    pub fn with_nav_for(mut self, builder: impl Fn(&Auth) -> Vec<NavLink> + Send + Sync + 'static) -> Self {
        self.nav_builder = Some(Arc::new(builder));
        self
    }

    /// Real, cookie-based session login — the only way this dialect's
    /// server-rendered screens (no client-side JS) can carry an
    /// identity across requests without an `Authorization` header on
    /// every request. Registers `GET`/`POST {path}` (the login form and
    /// its submission) and `POST {path}/logout`. `verify` checks a
    /// submitted username/password and returns the session's roles on
    /// success — this crate has no opinion on where credentials live.
    /// Successful logins redirect to "/" unless `with_login_landing` is
    /// used.
    pub fn with_login(mut self, path: &'static str, verify: impl Fn(&str, &str) -> Option<Vec<String>> + Send + Sync + 'static) -> Self {
        self.login = Some(LoginConfig {
            path: path.to_string(),
            verify: Arc::new(verify),
            landing: None,
        });
        self
    }

    /// Same as `with_login`, but the post-login redirect target is
    /// chosen by `landing(auth)` from the newly created session. Use
    /// this with `nirdosha_rt::landing!` or `nirdosha_rt::app_shell!`.
    pub fn with_login_landing(
        mut self,
        path: &'static str,
        verify: impl Fn(&str, &str) -> Option<Vec<String>> + Send + Sync + 'static,
        landing: impl Fn(&Auth) -> &'static str + Send + Sync + 'static,
    ) -> Self {
        self.login = Some(LoginConfig {
            path: path.to_string(),
            verify: Arc::new(verify),
            landing: Some(Arc::new(landing)),
        });
        self
    }

    /// Real, non-wildcard CORS: a cross-origin browser caller from one
    /// of `origins` gets its own origin reflected back (never `*`, see
    /// this struct's own `allowed_origins` doc comment) plus
    /// `Access-Control-Allow-Credentials: true` so its cookie-carrying
    /// `fetch()` calls actually work; any other origin gets no CORS
    /// headers at all, which every browser treats as a hard deny. Empty
    /// (never calling this) keeps today's behavior: no CORS headers,
    /// ever — an app with no cross-origin caller needs to opt into
    /// nothing.
    pub fn with_cors(mut self, origins: Vec<&'static str>) -> Self {
        self.allowed_origins = origins.into_iter().map(String::from).collect();
        self
    }

    /// Fixed-window, per-peer-IP rate limiting on `paths` (most
    /// relevant to `with_login`'s own login path, to bound brute-force
    /// throughput -- but takes an arbitrary path list since any handler
    /// might want the same protection). See `Router::rate_limit`'s own
    /// doc comment for the one real scope limit: this only ever
    /// triggers through `serve_until`'s real accept loop.
    pub fn with_rate_limit(mut self, paths: Vec<&'static str>, max_per_window: u32, window: std::time::Duration) -> Self {
        self.rate_limit = Some(RateLimitRule {
            paths: paths.into_iter().map(String::from).collect(),
            max_per_window,
            window,
            limiter: Arc::new(ratelimit::RateLimiter::new()),
        });
        self
    }

    /// The fleet-wide (Redis-backed) sibling to `with_rate_limit` —
    /// same fixed-window-per-peer-IP shape, but the count is shared
    /// across every process pointed at `redis_url` instead of held
    /// per-process. Fails to construct (`Result`, not a panic) only if
    /// `redis_url` itself is malformed; an *unreachable* Redis at
    /// request time is `check_fleet_rate_limit`'s own concern (it fails
    /// open, disclosed there). `paths` may overlap with `with_rate_limit`'s
    /// own — both would apply if configured, a per-process backstop on
    /// top of the fleet-wide one, not mutually exclusive.
    #[cfg(feature = "fleet-rate-limit")]
    pub fn with_fleet_rate_limit(mut self, paths: Vec<&'static str>, max_per_window: u32, window: std::time::Duration, redis_url: &str) -> Result<Self, redis::RedisError> {
        self.fleet_rate_limit = Some(FleetRateLimitRule {
            paths: paths.into_iter().map(String::from).collect(),
            max_per_window,
            window,
            limiter: Arc::new(fleet_ratelimit::FleetRateLimiter::new(redis_url)?),
        });
        Ok(self)
    }

    /// Picks `serve_until`'s transport strategy — see [`Runtime`]'s own
    /// doc comment. Only ever matters via `serve_until`/`serve`;
    /// `dispatch` called directly is identical either way.
    pub fn with_runtime(mut self, runtime: Runtime) -> Self {
        self.runtime = runtime;
        self
    }

    /// RFC 9449 (DPoP): `false` (default, unchanged behavior) means an
    /// ordinary bearer token is enough, same as every router before
    /// this existed. `true` additionally requires a valid `DPoP` header
    /// on every request that also carries an `Authorization: Bearer`
    /// header — proof-of-possession over the token, checked in
    /// `check_dpop`. Never inferred, never on by default: an app opts
    /// in only once it actually issues sender-constrained tokens (its
    /// own `authenticate` closure calling `Auth::with_cnf_jkt` after
    /// verifying a real token's `cnf.jkt` claim).
    #[cfg(feature = "dpop")]
    pub fn with_sender_constrained_tokens(mut self) -> Self {
        self.require_dpop = true;
        self
    }

    /// Terminates TLS directly in this process (`serve_until`'s own
    /// transport, both `Sync`/`Async`) instead of speaking plain HTTP
    /// only and assuming a deployer's reverse proxy handles it — the
    /// prior, and still available (`with_tls` never called), default.
    /// `cert_pem`/`key_pem` are the real PEM bytes a deployment's own
    /// certificate/key files already contain (ACME, a mounted secret,
    /// a local file — this crate has no opinion on where they come
    /// from). Also turns on `Strict-Transport-Security` on every
    /// response (`security_headers`'s own doc comment) — sending that
    /// header is only ever honest once this process is actually the
    /// one terminating TLS.
    #[cfg(feature = "tls")]
    pub fn with_tls(mut self, cert_pem: &[u8], key_pem: &[u8]) -> Result<Self, String> {
        self.tls = Some(Arc::new(tls::TlsConfig::from_pem(cert_pem, key_pem)?));
        Ok(self)
    }

    ungated_method!(get, "GET");
    ungated_method!(post, "POST");
    ungated_method!(put, "PUT");
    ungated_method!(delete, "DELETE");

    gated_method!(get_gated, "GET");
    gated_method!(post_gated, "POST");
    gated_method!(put_gated, "PUT");
    gated_method!(delete_gated, "DELETE");

    gated_claim_method!(get_gated_claim, "GET");
    gated_claim_method!(post_gated_claim, "POST");
    gated_claim_method!(put_gated_claim, "PUT");
    gated_claim_method!(delete_gated_claim, "DELETE");

    /// An ungated route (no `RoleProof<R>` required to view it at all)
    /// whose handler still gets the resolved `Auth` — for content that
    /// is *visible* to everyone but *varies* per viewer (e.g.
    /// `dashboard!`'s per-widget `requires_role`, which hides a widget
    /// from a viewer lacking the role rather than gating the whole
    /// page). Resolves the same way a gated route does: session cookie
    /// first, then the app's own `authenticate`.
    pub fn get_with_auth(
        mut self,
        path: &'static str,
        summary: &'static str,
        handler: impl Fn(&Request, &PathParams, &Auth) -> Response + Send + Sync + 'static,
    ) -> Self {
        let authenticate = self.authenticate.clone();
        let sessions = self.sessions.clone();
        let wrapped = move |req: &Request, params: &PathParams| -> Response {
            let auth = session_auth(&sessions, req).unwrap_or_else(|| authenticate(req));
            handler(req, params, &auth)
        };
        self.routes.push(Route {
            method: "GET",
            template: PathTemplate::parse(path),
            summary,
            required_role: None,
            required_claim: None,
            handler: Arc::new(wrapped),
        });
        self
    }

    /// Route one already-parsed request. `GET /openapi.json` is
    /// answered here directly, before the route table — it always
    /// exists, computed fresh from the final route list, and cannot be
    /// shadowed by an app forgetting to register it. Login/logout (if
    /// configured) are handled the same way, then every HTML response
    /// gets the nav bar spliced in.
    pub fn dispatch(&self, req: &Request) -> Response {
        self.dispatch_from_peer(req, None)
    }

    /// `serve_until`'s own entry point -- identical to `dispatch` except
    /// it also has a real peer IP to rate-limit against. `peer: None`
    /// (what `dispatch` itself passes) always skips the rate-limit
    /// check entirely, never fails open on a *configured* limit in a
    /// way that would be a false negative under real traffic -- see
    /// `Router::rate_limit`'s own doc comment for why that's the
    /// correct, disclosed scope rather than a gap.
    fn dispatch_from_peer(&self, req: &Request, peer: Option<IpAddr>) -> Response {
        if req.method == "OPTIONS" {
            return self.cors_preflight_response(req);
        }
        if let Some(rule) = &self.rate_limit {
            let path = req.path_without_query();
            if rule.paths.iter().any(|p| p == path) {
                if let Some(ip) = peer {
                    if !rule.limiter.check(ip, rule.max_per_window, rule.window) {
                        return self.apply_cors(req, Response::text(429, "rate limited"));
                    }
                }
            }
        }
        if let Some(resp) = self.check_fleet_rate_limit(req, peer) {
            return self.apply_cors(req, resp);
        }
        if let Some(resp) = self.check_dpop(req) {
            return self.apply_cors(req, resp);
        }
        let response = self.dispatch_authenticated(req);
        self.apply_cors(req, response)
    }

    /// `Some(429)` if a `with_fleet_rate_limit`-configured path's shared
    /// count is already past its limit; `None` otherwise, including
    /// when no fleet limit is configured, this request's path isn't one
    /// of the configured ones, there's no real peer IP (`dispatch`
    /// called directly), or Redis itself is unreachable. That last case
    /// is a deliberate fail-*open* choice — a rate limiter that also
    /// takes the whole fleet down when its own Redis has a bad moment
    /// would trade a real availability outage for a soft abuse-bound
    /// that `with_rate_limit`'s own per-process backstop still partially
    /// covers -- logged loudly (`eprintln!`), never silently.
    #[cfg(feature = "fleet-rate-limit")]
    fn check_fleet_rate_limit(&self, req: &Request, peer: Option<IpAddr>) -> Option<Response> {
        let rule = self.fleet_rate_limit.as_ref()?;
        let path = req.path_without_query();
        if !rule.paths.iter().any(|p| p == path) {
            return None;
        }
        let ip = peer?;
        match rule.limiter.check(ip, rule.max_per_window, rule.window) {
            Ok(true) => None,
            Ok(false) => Some(Response::text(429, "rate limited")),
            Err(e) => {
                eprintln!("nirdosha-rt: fleet rate limiter's Redis is unreachable, failing open for this request: {e}");
                None
            }
        }
    }

    #[cfg(not(feature = "fleet-rate-limit"))]
    fn check_fleet_rate_limit(&self, _req: &Request, _peer: Option<IpAddr>) -> Option<Response> {
        None
    }

    /// RFC 9449 (DPoP) enforcement — only ever does anything once
    /// `with_sender_constrained_tokens` was called. `Some(response)`
    /// means reject with that response (always a `401`); `None` means
    /// either this check doesn't apply (no `Authorization: Bearer`
    /// header at all — an anonymous or non-bearer request is a
    /// different gate's problem) or it passed. Fails closed at every
    /// step: a bearer token whose `Auth` carries no `cnf.jkt` at all
    /// (this deployment requires sender-constrained tokens but the
    /// token itself wasn't issued as one), no `DPoP` header, a proof
    /// that doesn't verify, or a replayed `jti` are all a real `401`,
    /// never silently accepted.
    #[cfg(feature = "dpop")]
    fn check_dpop(&self, req: &Request) -> Option<Response> {
        if !self.require_dpop {
            return None;
        }
        let auth_header = req.header("authorization")?;
        let token = auth_header.strip_prefix("Bearer ").or_else(|| auth_header.strip_prefix("bearer "))?;
        let auth = (self.authenticate)(req);
        let Some(expected_jkt) = auth.cnf_jkt() else {
            return Some(Response::text(401, "this access token has no `cnf.jkt` binding -- it was not issued as a sender-constrained token, and this server requires one"));
        };
        let Some(proof) = req.header("dpop") else {
            return Some(Response::text(401, "this server requires a `DPoP` header (sender-constrained tokens only, RFC 9449)"));
        };
        let host = req.header("host").unwrap_or("");
        let scheme = if self.tls_active() { "https" } else { "http" };
        let url = format!("{scheme}://{host}{}", req.path_without_query());
        let expected_ath = dpop::access_token_hash(token);
        let now = std::time::SystemTime::now().duration_since(std::time::UNIX_EPOCH).map(|d| d.as_secs() as i64).unwrap_or(0);
        match dpop::verify_proof(proof, &req.method, &url, &expected_ath, expected_jkt, DPOP_PROOF_FRESHNESS_WINDOW_SECS, now) {
            Ok(verified) => {
                if !self.dpop_replay.check_and_record(&verified.jti, std::time::Duration::from_secs(DPOP_PROOF_FRESHNESS_WINDOW_SECS as u64)) {
                    Some(Response::text(401, "this DPoP proof has already been used (replay)"))
                } else {
                    None
                }
            }
            Err(e) => Some(Response::text(401, &format!("invalid DPoP proof: {e}"))),
        }
    }

    #[cfg(not(feature = "dpop"))]
    fn check_dpop(&self, _req: &Request) -> Option<Response> {
        None
    }

    /// The old body of `dispatch`, unchanged — login/logout, then the
    /// route table, then the nav bar splice. Split out so `dispatch`
    /// itself can apply CORS headers to *every* response this produces,
    /// including its several early returns, from one single place
    /// rather than repeating the same header injection at each return
    /// site.
    fn dispatch_authenticated(&self, req: &Request) -> Response {
        let path = req.path_without_query().to_string();

        if let Some(login) = &self.login {
            if path == login.path && req.method == "GET" {
                return self.with_nav_bar(req, Response::html(200, login_page_html(&login.path, None)));
            }
            if path == login.path && req.method == "POST" {
                let form = req.form_or_json();
                let username = form.get("username").cloned().unwrap_or_default();
                let password = form.get("password").cloned().unwrap_or_default();
                let resp = match (login.verify)(&username, &password) {
                    Some(roles) => {
                        let session_id = generate_session_id();
                        self.sessions.lock().unwrap().insert(session_id.clone(), (username.clone(), roles.clone()));
                        let auth = Auth::login(username, &roles.iter().map(|r| r.as_str()).collect::<Vec<_>>());
                        let target = login.landing.as_ref().map(|l| l(&auth)).unwrap_or("/");
                        let mut resp = Response::redirect(target);
                        resp.extra_headers.push(("Set-Cookie".to_string(), format!("{SESSION_COOKIE}={session_id}; {SESSION_COOKIE_ATTRS}")));
                        resp
                    }
                    None => Response::html(401, login_page_html(&login.path, Some("invalid username or password"))),
                };
                return self.with_nav_bar(req, resp);
            }
            let logout_path = format!("{}/logout", login.path.trim_end_matches('/'));
            if path == logout_path && req.method == "POST" {
                if let Some(sid) = req.cookie(SESSION_COOKIE) {
                    self.sessions.lock().unwrap().remove(&sid);
                }
                let mut resp = Response::redirect("/");
                resp.extra_headers.push(("Set-Cookie".to_string(), format!("{SESSION_COOKIE}=; {SESSION_COOKIE_ATTRS}; Max-Age=0")));
                return resp;
            }
        }

        let response = self.dispatch_routes(&path, req);
        self.with_nav_bar(req, response)
    }

    fn dispatch_routes(&self, path: &str, req: &Request) -> Response {
        if req.method == "GET" && path == "/openapi.json" {
            return Response::json(200, &self.openapi_document());
        }
        let mut path_matched_some_method = false;
        for route in &self.routes {
            if let Some(params) = route.template.matches(path) {
                if route.method == req.method {
                    return (route.handler)(req, &params);
                }
                path_matched_some_method = true;
            }
        }
        if path_matched_some_method {
            Response::text(405, "method not allowed")
        } else {
            Response::not_found()
        }
    }

    /// Splices the nav bar (if configured) into an HTML response, right
    /// after `<body>` — `page_shell` always emits exactly one literal
    /// `<body>` tag, so a single first-occurrence replace is exact, not
    /// a heuristic.
    fn with_nav_bar(&self, req: &Request, mut response: Response) -> Response {
        if self.nav.is_empty() && self.nav_builder.is_none() && self.login.is_none() {
            return response;
        }
        if !response.content_type.starts_with("text/html") {
            return response;
        }
        let nav_html = self.render_nav(req);
        response.body = response.body.replacen("<body>", &format!("<body>{nav_html}"), 1);
        response
    }

    fn render_nav(&self, req: &Request) -> String {
        let auth = session_auth(&self.sessions, req).unwrap_or_else(|| (self.authenticate)(req));
        let links: Vec<NavLink> = self
            .nav_builder
            .as_ref()
            .map(|b| b(&auth))
            .unwrap_or_else(|| self.nav.clone());

        let mut html = String::from(
            "<nav style=\"margin:-2rem -2rem 2rem -2rem;padding:0.75rem 2rem;background:#f5f5f5;border-bottom:1px solid #ddd\">",
        );
        for link in &links {
            html.push_str(&format!("<a href=\"{}\" style=\"margin-right:1.5rem\">{}</a>", link.href, html_escape(link.label)));
        }
        if let Some(login) = &self.login {
            match session_auth(&self.sessions, req) {
                Some(auth) => {
                    html.push_str(&format!(
                        "<span style=\"float:right\">{} — <form method=\"post\" action=\"{}/logout\" style=\"display:inline;margin:0\"><button type=\"submit\">Logout</button></form></span>",
                        html_escape(auth.user()),
                        login.path.trim_end_matches('/'),
                    ));
                }
                None => {
                    html.push_str(&format!("<a href=\"{}\" style=\"float:right\">Login</a>", login.path));
                }
            }
        }
        html.push_str("</nav>");
        html
    }

    /// This request's `Origin` header, matched against `allowed_origins`
    /// -- `None` (no headers at all) when there's no `Origin` header, or
    /// it doesn't match any configured entry. Ported verbatim from
    /// `compiled-serve`'s own `cors_headers_for`/`parse_origin`/
    /// `origins_match` (that crate's own comments explain the scheme/
    /// default-port normalization; unchanged here).
    fn cors_headers_for(&self, req: &Request) -> Vec<(String, String)> {
        let Some(origin) = req.header("origin") else { return Vec::new() };
        if !self.allowed_origins.iter().any(|o| origins_match(o, origin)) {
            return Vec::new();
        }
        vec![
            ("Access-Control-Allow-Origin".to_string(), origin.to_string()),
            ("Access-Control-Allow-Credentials".to_string(), "true".to_string()),
            ("Vary".to_string(), "Origin".to_string()),
        ]
    }

    /// Every response gets these, unconditionally — `X-Content-Type-
    /// Options`/`X-Frame-Options`/`Referrer-Policy` cost nothing and
    /// have no legitimate use case they'd break. `Content-Security-
    /// Policy` allows `'unsafe-inline'` for both `script-src` and
    /// `style-src` deliberately, not by oversight: this dialect's own
    /// generated pages (`feed.rs`'s long-poll script,
    /// `showcase_screens.rs`, every `style="..."` attribute
    /// `render_nav`/the screen archetypes emit) rely on inline
    /// `<script>`/`style=` today, and a strict CSP with neither would
    /// break real, first-party output, not just close a hole. What it
    /// still does for real: no external origin can be loaded at all
    /// (`default-src 'self'`), no plugin content (`object-src 'none'`),
    /// and no framing (`frame-ancestors 'none'`, redundant with but
    /// stronger than `X-Frame-Options` for browsers that honor both).
    /// `Strict-Transport-Security` is added only when this connection
    /// is actually TLS-terminated by this process itself (`self.tls`) —
    /// sending it over a plain-HTTP-only deployment would tell a
    /// browser to *only* ever use HTTPS for this host, which is simply
    /// false for a deployment that never configured TLS at all.
    fn security_headers(&self) -> Vec<(String, String)> {
        let mut headers = vec![
            ("X-Content-Type-Options".to_string(), "nosniff".to_string()),
            ("X-Frame-Options".to_string(), "DENY".to_string()),
            ("Referrer-Policy".to_string(), "strict-origin-when-cross-origin".to_string()),
            (
                "Content-Security-Policy".to_string(),
                "default-src 'self'; script-src 'self' 'unsafe-inline'; style-src 'self' 'unsafe-inline'; \
                 img-src 'self' data:; object-src 'none'; frame-ancestors 'none'; base-uri 'self'"
                    .to_string(),
            ),
        ];
        if self.tls_active() {
            headers.push(("Strict-Transport-Security".to_string(), "max-age=31536000; includeSubDomains".to_string()));
        }
        headers
    }

    #[cfg(feature = "tls")]
    fn tls_active(&self) -> bool {
        self.tls.is_some()
    }

    #[cfg(not(feature = "tls"))]
    fn tls_active(&self) -> bool {
        false
    }

    fn apply_cors(&self, req: &Request, mut resp: Response) -> Response {
        resp.extra_headers.extend(self.cors_headers_for(req));
        resp.extra_headers.extend(self.security_headers());
        resp
    }

    /// A CORS preflight (`OPTIONS`) response — `204` either way; the
    /// actual allow/deny decision is entirely in whether `cors_headers_for`
    /// found a match, since an empty header set is what tells the
    /// browser to block the real request that would have followed.
    fn cors_preflight_response(&self, req: &Request) -> Response {
        let mut headers = self.cors_headers_for(req);
        if !headers.is_empty() {
            headers.push(("Access-Control-Allow-Methods".to_string(), "GET, POST, PUT, DELETE, OPTIONS".to_string()));
            headers.push(("Access-Control-Allow-Headers".to_string(), "Content-Type, Authorization, X-Requested-With".to_string()));
        }
        headers.extend(self.security_headers());
        Response { status: 204, content_type: "text/plain", body: String::new(), extra_headers: headers }
    }

    /// A minimal OpenAPI 3.0.3 document: paths, methods, summaries, and
    /// — for a gated route — a `security` entry naming the role
    /// `R::NAME` or the claim `(C::NAME, C::VALUE)` that route's
    /// handler actually checked at registration time. Not a schema
    /// generator: request/response bodies are not typed here.
    pub fn openapi_document(&self) -> serde_json::Value {
        let mut paths = serde_json::Map::new();
        for route in &self.routes {
            let key = route.template.as_openapi_path();
            let entry = paths
                .entry(key)
                .or_insert_with(|| serde_json::json!({}))
                .as_object_mut()
                .expect("path entries are always objects");
            let mut op = serde_json::json!({
                "summary": route.summary,
                "responses": { "200": { "description": "OK" } },
            });
            if let Some(role) = route.required_role {
                op["security"] = serde_json::json!([{ "nirdoshaRole": [role] }]);
            }
            if let Some((name, value)) = route.required_claim {
                op["security"] = serde_json::json!([{ "nirdoshaClaim": [format!("{name}={value}")] }]);
            }
            entry.insert(route.method.to_ascii_lowercase(), op);
        }
        serde_json::json!({
            "openapi": "3.0.3",
            "info": { "title": self.title, "version": self.version },
            "paths": serde_json::Value::Object(paths),
            "components": {
                "securitySchemes": {
                    "nirdoshaRole": {
                        "type": "apiKey",
                        "in": "header",
                        "name": "X-Nirdosha-Role-Doc",
                        "description": "Documentation only, mirroring the RoleProof<R> type actually enforced server-side (RFC 0020 Road 1/Road 2). Never authoritative on its own."
                    },
                    "nirdoshaClaim": {
                        "type": "apiKey",
                        "in": "header",
                        "name": "X-Nirdosha-Claim-Doc",
                        "description": "Documentation only, mirroring the ClaimProof<C> type actually enforced server-side. Never authoritative on its own."
                    }
                }
            }
        })
    }

    /// Serve on localhost with bounded concurrent connection workers.
    /// Retains the minimal HTTP transport: one recv per request, no keep-alive.
    pub fn serve(&self, port: u16) -> ! {
        let listener = std::net::TcpListener::bind(("127.0.0.1", port)).expect("listen");
        self.serve_until(listener, &std::sync::atomic::AtomicBool::new(false), ServeConfig::default())
            .expect("HTTP server failed");
        unreachable!("the permanent server has no shutdown signal")
    }

    /// Serve an already-bound listener until shutdown is requested,
    /// under whichever [`Runtime`] this router was built with
    /// (`with_runtime`, default `Async`). Both implementations honor
    /// the identical contract: excess connections (past
    /// `ServeConfig::max_connections`) are accepted then closed without
    /// being handled; accepting stops first, then every in-flight
    /// handler is drained before this returns; user handlers must
    /// eventually return (or, on the async side, eventually stop
    /// blocking the `spawn_blocking` thread they're running on).
    pub fn serve_until(&self, listener: std::net::TcpListener, shutdown: &std::sync::atomic::AtomicBool, config: ServeConfig) -> std::io::Result<()> {
        if config.io_timeout.is_zero() {
            return Err(std::io::Error::new(std::io::ErrorKind::InvalidInput, "io_timeout must be positive"));
        }
        match self.runtime {
            Runtime::Sync => self.serve_until_sync(listener, shutdown, config),
            Runtime::Async => self.serve_until_async(listener, shutdown, config),
        }
    }

    /// Today's original accept loop: one OS thread per accepted
    /// connection, bounded by `config.max_connections`. See
    /// `Runtime::Sync`'s own doc comment.
    fn serve_until_sync(&self, listener: std::net::TcpListener, shutdown: &std::sync::atomic::AtomicBool, config: ServeConfig) -> std::io::Result<()> {
        use std::sync::atomic::Ordering;
        listener.set_nonblocking(true)?;
        let shared_router = Arc::new(self.clone());
        let mut workers: Vec<std::thread::JoinHandle<()>> = Vec::new();
        let result = loop {
            let mut index = 0;
            while index < workers.len() {
                if workers[index].is_finished() {
                    crate::prelude::join(workers.swap_remove(index));
                } else {
                    index += 1;
                }
            }
            if shutdown.load(Ordering::Acquire) {
                break Ok(());
            }
            match listener.accept() {
                Ok((stream, peer_addr)) => {
                    if workers.len() >= config.max_connections.get() {
                        drop(stream);
                        continue;
                    }
                    let setup = stream.set_nonblocking(false)
                        .and_then(|_| stream.set_read_timeout(Some(config.io_timeout)))
                        .and_then(|_| stream.set_write_timeout(Some(config.io_timeout)));
                    if let Err(error) = setup {
                        break Err(error);
                    }
                    let router = shared_router.clone();
                    workers.push(crate::prelude::spawn(move || {
                        #[cfg(feature = "tls")]
                        if let Some(tls) = router.tls.clone() {
                            let _ = std::panic::catch_unwind(std::panic::AssertUnwindSafe(|| {
                                tls::handle_sync_connection(&tls, stream, |req| router.dispatch_from_peer(req, Some(peer_addr.ip())));
                            }));
                            return;
                        }
                        let conn = crate::prelude::Tcp::from_stream(stream);
                        let _ = std::panic::catch_unwind(std::panic::AssertUnwindSafe(|| {
                            let raw = conn.recv();
                            let response = match Request::parse(&raw) {
                                Some(req) => router.dispatch_from_peer(&req, Some(peer_addr.ip())),
                                None => Response::bad_request("malformed request"),
                            };
                            response.write_to(&conn);
                        }));
                        crate::prelude::stop(conn);
                    }));
                }
                Err(error) if error.kind() == std::io::ErrorKind::WouldBlock => {
                    std::thread::sleep(std::time::Duration::from_millis(5));
                }
                Err(error) if error.kind() == std::io::ErrorKind::Interrupted => {}
                Err(error) => break Err(error),
            }
        };
        drop(listener);
        for worker in workers {
            crate::prelude::join(worker);
        }
        result
    }

    /// A tokio-based accept loop: bounded async *tasks* (a
    /// `tokio::sync::Semaphore` sized to `config.max_connections`, not
    /// one OS thread per connection) with each handler invocation run
    /// via `tokio::task::spawn_blocking` -- handlers stay the exact
    /// same sync `Fn(&Request, &PathParams) -> Response` closures
    /// `dispatch_authenticated` already calls on the sync path; this
    /// never awaits a handler inline, so a handler that legitimately
    /// blocks (`communication_feed!`'s long-poll wait) never stalls the
    /// reactor's own worker threads, matching `serve_until_sync`'s own
    /// "a slow handler doesn't block other routes" guarantee via a
    /// different mechanism (a dedicated blocking-task thread pool
    /// instead of a dedicated OS thread per connection). Same contract
    /// as the sync path otherwise: an over-capacity connection is
    /// accepted then dropped without being handled (never left
    /// unaccepted in the kernel backlog, which is what a caller
    /// expecting a prompt, explicit connection close -- not an
    /// eventual timeout -- actually depends on); shutdown stops
    /// accepting first, then every spawned task is awaited before this
    /// returns.
    #[cfg(feature = "async-runtime")]
    fn serve_until_async(&self, listener: std::net::TcpListener, shutdown: &std::sync::atomic::AtomicBool, config: ServeConfig) -> std::io::Result<()> {
        use std::sync::atomic::Ordering;

        listener.set_nonblocking(true)?;
        let rt = tokio::runtime::Builder::new_multi_thread().enable_all().build()?;
        let shared_router = Arc::new(self.clone());

        rt.block_on(async move {
            let listener = tokio::net::TcpListener::from_std(listener)?;
            let semaphore = Arc::new(tokio::sync::Semaphore::new(config.max_connections.get()));
            let mut tasks: Vec<tokio::task::JoinHandle<()>> = Vec::new();

            let result: std::io::Result<()> = loop {
                let mut index = 0;
                while index < tasks.len() {
                    if tasks[index].is_finished() {
                        tasks.swap_remove(index);
                    } else {
                        index += 1;
                    }
                }
                if shutdown.load(Ordering::Acquire) {
                    break Ok(());
                }
                // A short poll tick, the same 5ms cadence
                // `serve_until_sync`'s own `WouldBlock` sleep uses --
                // gives the shutdown flag a bounded, real chance to be
                // rechecked instead of blocking on `accept()` forever.
                let accepted = tokio::time::timeout(std::time::Duration::from_millis(5), listener.accept()).await;
                let (stream, peer_addr) = match accepted {
                    Ok(Ok(pair)) => pair,
                    Ok(Err(error)) => break Err(error),
                    Err(_) => continue,
                };
                let Ok(permit) = Arc::clone(&semaphore).try_acquire_owned() else {
                    // Over capacity: accepted, then dropped without
                    // being handled -- the peer sees an immediate,
                    // explicit close (FIN/RST), never an unaccepted
                    // connection sitting in the kernel backlog until it
                    // times out on its own.
                    drop(stream);
                    continue;
                };
                let router = Arc::clone(&shared_router);
                let io_timeout = config.io_timeout;
                let peer_ip = peer_addr.ip();
                #[cfg(feature = "tls")]
                let tls_acceptor = self.tls.as_ref().map(|tls| tls::acceptor(tls));
                tasks.push(tokio::spawn(async move {
                    let _permit = permit;
                    #[cfg(feature = "tls")]
                    if let Some(acceptor) = tls_acceptor {
                        match acceptor.accept(stream).await {
                            Ok(tls_stream) => serve_one_async(tls_stream, io_timeout, peer_ip, router).await,
                            Err(_) => {} // handshake failed -- close with no response, same posture as any other malformed/incomplete request
                        }
                        return;
                    }
                    serve_one_async(stream, io_timeout, peer_ip, router).await;
                }));
            };
            drop(listener);
            for task in tasks {
                let _ = task.await;
            }
            result
        })
    }

    /// This crate was built with `--no-default-features` (no
    /// `async-runtime`, so no `tokio`) and something still requested
    /// `Runtime::Async` -- either explicitly via `with_runtime`, or by
    /// leaving `Router::new`'s own `Runtime::default()` in place. A
    /// real, honest `Err` (this crate's own posture everywhere else:
    /// never a silent downgrade to a different runtime than the one
    /// asked for), not a compile error at the call site and not a
    /// panic here.
    #[cfg(not(feature = "async-runtime"))]
    fn serve_until_async(&self, _listener: std::net::TcpListener, _shutdown: &std::sync::atomic::AtomicBool, _config: ServeConfig) -> std::io::Result<()> {
        Err(std::io::Error::new(
            std::io::ErrorKind::Unsupported,
            "Runtime::Async requires nirdosha-rt's `async-runtime` feature (on by default) -- either enable it, or call .with_runtime(Runtime::Sync)",
        ))
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    struct Admin;
    impl Role for Admin {
        const NAME: &'static str = "admin";
    }

    #[test]
    fn parses_method_path_headers_and_body() {
        let raw = "POST /api/products HTTP/1.1\r\nHost: x\r\nAuthorization: Bearer tok\r\n\r\n{\"name\":\"Widget\"}";
        let req = Request::parse(raw).unwrap();
        assert_eq!(req.method, "POST");
        assert_eq!(req.path, "/api/products");
        assert_eq!(req.header("authorization"), Some("Bearer tok"));
        assert_eq!(req.body, "{\"name\":\"Widget\"}");
    }

    #[test]
    fn query_string_is_parsed() {
        let req = Request {
            method: "GET".into(),
            path: "/api/products?q=widget&page=2".into(),
            headers: HashMap::new(),
            body: String::new(),
        };
        let q = req.query();
        assert_eq!(q.get("q"), Some(&"widget".to_string()));
        assert_eq!(q.get("page"), Some(&"2".to_string()));
    }

    #[test]
    fn form_urlencoded_body_is_parsed_with_percent_decoding() {
        let req = Request {
            method: "POST".into(),
            path: "/api/products".into(),
            headers: HashMap::new(),
            body: "name=Caf%C3%A9+Table&price_cents=999".into(),
        };
        let form = req.form_or_json();
        assert_eq!(form.get("name"), Some(&"Café Table".to_string()));
        assert_eq!(form.get("price_cents"), Some(&"999".to_string()));
    }

    #[test]
    fn json_body_is_parsed_the_same_way_form_is() {
        let mut headers = HashMap::new();
        headers.insert("content-type".to_string(), "application/json".to_string());
        let req = Request {
            method: "POST".into(),
            path: "/api/products".into(),
            headers,
            body: r#"{"name":"Widget","price_cents":999}"#.into(),
        };
        let form = req.form_or_json();
        assert_eq!(form.get("name"), Some(&"Widget".to_string()));
        assert_eq!(form.get("price_cents"), Some(&"999".to_string()));
    }

    #[test]
    fn html_escape_neutralizes_markup() {
        assert_eq!(html_escape("<script>alert('x')</script>"), "&lt;script&gt;alert(&#39;x&#39;)&lt;/script&gt;");
    }

    #[test]
    fn path_template_extracts_params() {
        let t = PathTemplate::parse("/api/products/{id}");
        let params = t.matches("/api/products/42").unwrap();
        assert_eq!(params.get("id"), Some("42"));
        assert!(t.matches("/api/products").is_none());
        assert!(t.matches("/api/products/42/extra").is_none());
    }

    fn req(method: &str, path: &str) -> Request {
        Request {
            method: method.into(),
            path: path.into(),
            headers: HashMap::new(),
            body: String::new(),
        }
    }

    #[test]
    fn unknown_path_is_404_known_path_wrong_method_is_405() {
        let router = Router::new(|_| Auth::login("anon", &[])).get("/api/products", "list", |_, _| Response::text(200, "ok"));
        assert_eq!(router.dispatch(&req("GET", "/nope")).status, 404);
        assert_eq!(router.dispatch(&req("POST", "/api/products")).status, 405);
        assert_eq!(router.dispatch(&req("GET", "/api/products")).status, 200);
    }

    /// Most apps this dialect targets are I/O-bound, not CPU-bound --
    /// `Router::new` must default to `Runtime::Async` whenever that
    /// transport is actually compiled in, without anyone having to call
    /// `with_runtime` at all, and `with_runtime` must actually change it
    /// (this crate's own tests, and any app that wants the opt-out,
    /// both depend on the builder really taking effect, not just
    /// type-checking). Under `--no-default-features` (no
    /// `async-runtime`, so no working `Async` transport at all) the
    /// default is `Sync` instead -- `Runtime::default()`'s own doc
    /// comment has the "why."
    #[test]
    fn router_defaults_to_the_async_runtime_and_with_runtime_overrides_it() {
        let router = Router::new(|_| Auth::login("anon", &[]));
        #[cfg(feature = "async-runtime")]
        assert_eq!(router.runtime, Runtime::Async);
        #[cfg(not(feature = "async-runtime"))]
        assert_eq!(router.runtime, Runtime::Sync);
        let router = router.with_runtime(Runtime::Sync);
        assert_eq!(router.runtime, Runtime::Sync);
    }

    /// Only meaningful (and only compiled) in a `--no-default-features`
    /// build, where `Runtime::Async` -- still `Router::new`'s own
    /// default even here -- has no real implementation behind it.
    /// Requesting it must be a real, honest `Err` naming the missing
    /// feature, never a panic or a silent fallback to `Sync`.
    #[cfg(not(feature = "async-runtime"))]
    #[test]
    fn async_runtime_without_the_feature_is_a_clear_error_not_a_panic() {
        // `Router::new`'s own default is feature-aware (`Sync` here,
        // since this test only compiles without `async-runtime`) -- so
        // this has to *explicitly* request `Async` to reach the error
        // path this test is actually about.
        let router = Router::new(|_| Auth::login("anon", &[])).with_runtime(Runtime::Async).get("/", "root", |_, _| Response::text(200, "ok"));
        let listener = std::net::TcpListener::bind("127.0.0.1:0").unwrap();
        let shutdown = std::sync::atomic::AtomicBool::new(false);
        let err = router.serve_until(listener, &shutdown, ServeConfig::default()).unwrap_err();
        assert_eq!(err.kind(), std::io::ErrorKind::Unsupported);
        assert!(err.to_string().contains("async-runtime"), "got: {err}");
    }

    #[test]
    fn openapi_json_always_exists_with_no_registration() {
        let router = Router::new(|_| Auth::login("anon", &[]));
        let resp = router.dispatch(&req("GET", "/openapi.json"));
        assert_eq!(resp.status, 200);
        let doc: serde_json::Value = serde_json::from_str(&resp.body).unwrap();
        assert_eq!(doc["openapi"], "3.0.3");
    }

    #[test]
    fn gated_route_enforces_the_real_role_proof() {
        let router = Router::new(|r| {
            let roles: Vec<&str> = r.header("x-roles").map(|s| s.split(',').collect()).unwrap_or_default();
            Auth::login("user", &roles)
        })
        .post_gated::<Admin>("/api/products", "create", |_, _, _proof| Response::text(201, "created"));

        let mut denied = req("POST", "/api/products");
        assert_eq!(router.dispatch(&denied).status, 403);

        denied.headers.insert("x-roles".into(), "admin".into());
        assert_eq!(router.dispatch(&denied).status, 201);
    }

    #[test]
    fn openapi_reports_the_same_role_the_gate_checked() {
        let router = Router::new(|_| Auth::login("anon", &[]))
            .post_gated::<Admin>("/api/products", "create", |_, _, _proof| Response::text(201, "created"));
        let doc = router.openapi_document();
        let role = &doc["paths"]["/api/products"]["post"]["security"][0]["nirdoshaRole"][0];
        assert_eq!(role, "admin");
    }

    struct CardiologyDept;
    impl Claim for CardiologyDept {
        const NAME: &'static str = "department";
        const VALUE: &'static str = "cardiology";
    }

    /// `get_gated_claim`'s real enforcement (`Auth::prove_claim::<C>()`
    /// via the router) -- the same shape
    /// `gated_route_enforces_the_real_role_proof` already proves for
    /// roles, ported to claims: absent claim -> 403, wrong value for
    /// the right claim name -> still 403, exact name+value -> 200.
    #[test]
    fn claim_gated_route_enforces_the_real_claim_proof() {
        let router = Router::new(|r| Auth::login("user", &[]).with_claims(&r.header("x-department").map(|d| vec![("department", d)]).unwrap_or_default()))
            .get_gated_claim::<CardiologyDept>("/api/cardiology-report", "report", |_, _, _proof| Response::text(200, "ok"));

        let mut denied = req("GET", "/api/cardiology-report");
        assert_eq!(router.dispatch(&denied).status, 403);

        denied.headers.insert("x-department".into(), "oncology".into());
        assert_eq!(router.dispatch(&denied).status, 403, "the right claim name with the wrong value must still be denied");

        denied.headers.insert("x-department".into(), "cardiology".into());
        assert_eq!(router.dispatch(&denied).status, 200);
    }

    #[test]
    fn openapi_reports_the_same_claim_the_gate_checked() {
        let router = Router::new(|_| Auth::login("anon", &[]))
            .get_gated_claim::<CardiologyDept>("/api/cardiology-report", "report", |_, _, _proof| Response::text(200, "ok"));
        let doc = router.openapi_document();
        let claim = &doc["paths"]["/api/cardiology-report"]["get"]["security"][0]["nirdoshaClaim"][0];
        assert_eq!(claim, "department=cardiology");
    }

    fn cookie_req(method: &str, path: &str, cookie: Option<&str>) -> Request {
        let mut headers = HashMap::new();
        if let Some(c) = cookie {
            headers.insert("cookie".to_string(), c.to_string());
        }
        Request { method: method.into(), path: path.into(), headers, body: String::new() }
    }

    fn cookie_from_set_cookie(resp: &Response) -> String {
        let raw = resp
            .extra_headers
            .iter()
            .find(|(k, _)| k == "Set-Cookie")
            .map(|(_, v)| v.clone())
            .expect("no Set-Cookie header");
        raw.split(';').next().unwrap().to_string()
    }

    fn form(pairs: &[(&str, &str)]) -> Request {
        let body = pairs.iter().map(|(k, v)| format!("{k}={v}")).collect::<Vec<_>>().join("&");
        Request { method: "POST".into(), path: "/login".into(), headers: HashMap::new(), body }
    }

    #[test]
    fn login_mints_a_session_cookie_that_a_gated_route_then_accepts() {
        let router = Router::new(|_| Auth::login("anon", &[]))
            .with_login("/login", |u, p| if u == "alice" && p == "secret" { Some(vec!["admin".to_string()]) } else { None })
            .get_gated::<Admin>("/secret", "secret", |_, _, _proof| Response::text(200, "ok"));

        // Wrong password: no session minted.
        let bad = router.dispatch(&form(&[("username", "alice"), ("password", "wrong")]));
        assert_eq!(bad.status, 401);
        assert!(bad.extra_headers.iter().all(|(k, _)| k != "Set-Cookie"));

        // Right password: a session cookie is minted...
        let ok = router.dispatch(&form(&[("username", "alice"), ("password", "secret")]));
        assert_eq!(ok.status, 302);
        let cookie = cookie_from_set_cookie(&ok);

        // ...and it alone (no Authorization header) satisfies the admin gate.
        let secret = router.dispatch(&cookie_req("GET", "/secret", Some(&cookie)));
        assert_eq!(secret.status, 200);

        // A request with no cookie at all is still refused.
        let denied = router.dispatch(&cookie_req("GET", "/secret", None));
        assert_eq!(denied.status, 403);
    }

    #[test]
    fn logout_clears_the_session() {
        let router = Router::new(|_| Auth::login("anon", &[]))
            .with_login("/login", |_, _| Some(vec!["admin".to_string()]))
            .get_gated::<Admin>("/secret", "secret", |_, _, _proof| Response::text(200, "ok"));

        let ok = router.dispatch(&form(&[("username", "x"), ("password", "y")]));
        let cookie = cookie_from_set_cookie(&ok);
        assert_eq!(router.dispatch(&cookie_req("GET", "/secret", Some(&cookie))).status, 200);

        let logout_req = Request { method: "POST".into(), path: "/login/logout".into(), headers: {
            let mut h = HashMap::new();
            h.insert("cookie".to_string(), cookie.clone());
            h
        }, body: String::new() };
        let logout_resp = router.dispatch(&logout_req);
        assert_eq!(logout_resp.status, 302);

        // The same (now-invalidated) cookie no longer satisfies the gate.
        assert_eq!(router.dispatch(&cookie_req("GET", "/secret", Some(&cookie))).status, 403);
    }

    #[test]
    fn nav_bar_shows_login_when_anonymous_and_logout_when_authenticated() {
        let router = Router::new(|_| Auth::login("anon", &[]))
            .with_nav(vec![NavLink { label: "Home", href: "/" }])
            .with_login("/login", |_, _| Some(vec!["admin".to_string()]))
            .get("/", "home", |_, _| Response::html(200, "<html><body>hi</body></html>"));

        let anon = router.dispatch(&cookie_req("GET", "/", None));
        assert!(anon.body.contains("Login"), "got: {}", anon.body);
        assert!(!anon.body.contains("Logout"));

        let login_resp = router.dispatch(&form(&[("username", "x"), ("password", "y")]));
        let cookie = cookie_from_set_cookie(&login_resp);
        let authed = router.dispatch(&cookie_req("GET", "/", Some(&cookie)));
        assert!(authed.body.contains("Logout"), "got: {}", authed.body);
    }

    /// The minted session cookie carries `Secure`/`SameSite=Strict` on
    /// top of the pre-existing `HttpOnly` -- a VAPT-obvious finding
    /// (session cookie missing `Secure`/`SameSite`) that used to be real
    /// against this router and now isn't.
    #[test]
    fn session_cookie_carries_secure_and_samesite_attributes() {
        let router = Router::new(|_| Auth::login("anon", &[])).with_login("/login", |_, _| Some(vec!["admin".to_string()]));
        let login_resp = router.dispatch(&form(&[("username", "x"), ("password", "y")]));
        let set_cookie = login_resp.extra_headers.iter().find(|(k, _)| k == "Set-Cookie").map(|(_, v)| v.clone()).expect("no Set-Cookie header");
        assert!(set_cookie.contains("Secure"), "got: {set_cookie}");
        assert!(set_cookie.contains("SameSite=Strict"), "got: {set_cookie}");
        assert!(set_cookie.contains("HttpOnly"), "got: {set_cookie}");

        let logout_req = Request {
            method: "POST".into(),
            path: "/login/logout".into(),
            headers: HashMap::new(),
            body: String::new(),
        };
        let logout_resp = router.dispatch(&logout_req);
        let cleared = logout_resp.extra_headers.iter().find(|(k, _)| k == "Set-Cookie").map(|(_, v)| v.clone()).expect("no Set-Cookie header");
        assert!(cleared.contains("Secure"), "got: {cleared}");
        assert!(cleared.contains("SameSite=Strict"), "got: {cleared}");
    }

    fn req_with_origin(method: &str, path: &str, origin: &str) -> Request {
        let mut headers = HashMap::new();
        headers.insert("origin".to_string(), origin.to_string());
        Request { method: method.into(), path: path.into(), headers, body: String::new() }
    }

    /// A configured origin gets its own value reflected back plus
    /// `Access-Control-Allow-Credentials: true`, on both a real response
    /// and an `OPTIONS` preflight -- and never a wildcard, which a
    /// credentialed router (every gated route relies on the session
    /// cookie) can never safely send.
    #[test]
    fn cors_reflects_only_a_configured_origin_never_a_wildcard() {
        let router = Router::new(|_| Auth::login("anon", &[]))
            .with_cors(vec!["https://app.example.com"])
            .get("/api/products", "list", |_, _| Response::text(200, "ok"));

        let allowed = router.dispatch(&req_with_origin("GET", "/api/products", "https://app.example.com"));
        let acao = allowed.extra_headers.iter().find(|(k, _)| k == "Access-Control-Allow-Origin").map(|(_, v)| v.clone());
        assert_eq!(acao, Some("https://app.example.com".to_string()));
        assert!(allowed.extra_headers.iter().any(|(k, v)| k == "Access-Control-Allow-Credentials" && v == "true"));
        assert!(!allowed.extra_headers.iter().any(|(_, v)| v == "*"), "must never reflect a wildcard");

        let denied = router.dispatch(&req_with_origin("GET", "/api/products", "https://evil.example.com"));
        assert!(!denied.extra_headers.iter().any(|(k, _)| k == "Access-Control-Allow-Origin"), "an unconfigured origin must get no CORS headers at all");

        let preflight = router.dispatch(&req_with_origin("OPTIONS", "/api/products", "https://app.example.com"));
        assert_eq!(preflight.status, 204);
        assert!(preflight.extra_headers.iter().any(|(k, _)| k == "Access-Control-Allow-Origin"));
        assert!(preflight.extra_headers.iter().any(|(k, _)| k == "Access-Control-Allow-Methods"));
    }

    /// The default (`with_cors` never called) emits no CORS headers at
    /// all, even for an `Origin` header a caller sends anyway -- an app
    /// with no cross-origin caller opts into nothing by default.
    #[test]
    fn no_cors_configured_means_no_cors_headers_at_all() {
        let router = Router::new(|_| Auth::login("anon", &[])).get("/api/products", "list", |_, _| Response::text(200, "ok"));
        let resp = router.dispatch(&req_with_origin("GET", "/api/products", "https://app.example.com"));
        assert!(resp.extra_headers.iter().all(|(k, _)| k != "Access-Control-Allow-Origin"));
    }

    // -------------------------------------------------------------------
    // Property-based tests. White-box (this module's own `PathTemplate`),
    // not just the handful of examples above.
    // -------------------------------------------------------------------
    mod properties {
        use super::*;
        use proptest::prelude::*;

        fn segment_strategy() -> impl Strategy<Value = String> {
            "[a-z][a-z0-9_]{1,8}"
        }

        fn percent_encode(s: &str) -> String {
            s.bytes()
                .map(|b| match b {
                    b'A'..=b'Z' | b'a'..=b'z' | b'0'..=b'9' | b'-' | b'_' | b'.' | b'~' => (b as char).to_string(),
                    _ => format!("%{b:02X}"),
                })
                .collect()
        }

        proptest! {
            /// Percent-decoding round-trips arbitrary Unicode strings
            /// through an ordinary percent-encoder — the byte-buffer
            /// decode (not a naive char-by-char one) has to get
            /// multi-byte UTF-8 right, not just ASCII.
            #[test]
            fn url_decode_round_trips_arbitrary_strings(s in ".*") {
                let form = format!("k={}", percent_encode(&s));
                let parsed = parse_urlencoded(&form);
                prop_assert_eq!(parsed.get("k").map(String::as_str), Some(s.as_str()));
            }

            /// html_escape's output never contains a raw `<` or `>`,
            /// for any input — the property that actually makes it
            /// safe to interpolate into HTML.
            #[test]
            fn html_escape_leaves_no_raw_markup_delimiters(s in ".*") {
                let escaped = html_escape(&s);
                prop_assert!(!escaped.contains('<'));
                prop_assert!(!escaped.contains('>'));
            }
        }

        proptest! {
            /// For any literal path built from arbitrary segments, the
            /// template built from those exact literal segments matches
            /// that path and extracts no params.
            #[test]
            fn literal_template_matches_its_own_path(segs in prop::collection::vec(segment_strategy(), 1..5)) {
                let path = format!("/{}", segs.join("/"));
                let template = PathTemplate::parse(&path);
                let params = template.matches(&path);
                prop_assert!(params.is_some());
            }

            /// A `{param}` segment always extracts exactly the concrete
            /// value that occupied that position, for any concrete value
            /// that itself looks like an ordinary path segment.
            #[test]
            fn param_segment_extracts_the_concrete_value(
                prefix in segment_strategy(),
                param_name in segment_strategy(),
                value in segment_strategy(),
            ) {
                let template = PathTemplate::parse(&format!("/{prefix}/{{{param_name}}}"));
                let params = template.matches(&format!("/{prefix}/{value}")).unwrap();
                prop_assert_eq!(params.get(&param_name), Some(value.as_str()));
            }

            /// Changing any literal segment to a different literal never
            /// matches.
            #[test]
            fn mismatched_literal_never_matches(
                seg in segment_strategy(),
                other in segment_strategy(),
            ) {
                prop_assume!(seg != other);
                let template = PathTemplate::parse(&format!("/api/{seg}"));
                let other_path = format!("/api/{other}");
                let no_match = template.matches(&other_path).is_none();
                prop_assert!(no_match);
            }

            /// A gated route's real enforcement (`Auth::prove::<Admin>()`
            /// via the router) succeeds if and only if the session's role
            /// set actually contains `"admin"` — the property this whole
            /// mechanism exists for. Fuzzed over arbitrary role-set
            /// contents, not just the one hand-picked example above.
            #[test]
            fn gated_dispatch_succeeds_iff_role_present(
                roles in prop::collection::vec(segment_strategy(), 0..4),
            ) {
                let has_admin = roles.iter().any(|r| r == "admin");
                let router = Router::new(move |r: &Request| {
                    let roles: Vec<&str> = r.header("x-roles").map(|s| s.split(',').filter(|s| !s.is_empty()).collect()).unwrap_or_default();
                    Auth::login("user", &roles)
                })
                .post_gated::<Admin>("/api/products", "create", |_, _, _proof| Response::text(201, "created"));

                let mut request = req("POST", "/api/products");
                request.headers.insert("x-roles".into(), roles.join(","));
                let status = router.dispatch(&request).status;
                prop_assert_eq!(status == 201, has_admin);
                prop_assert!(status == 201 || status == 403);
            }

            /// Any request whose path doesn't match a registered route's
            /// template is always 404, regardless of method.
            #[test]
            fn unregistered_path_is_always_404(
                registered in segment_strategy(),
                requested in segment_strategy(),
                method in "GET|POST|PUT|DELETE",
            ) {
                prop_assume!(registered != requested);
                let path: &'static str = Box::leak(format!("/{registered}").into_boxed_str());
                let router = Router::new(|_| Auth::login("anon", &[]))
                    .get(path, "x", |_, _| Response::text(200, "ok"));
                let status = router.dispatch(&req(&method, &format!("/{requested}"))).status;
                prop_assert_eq!(status, 404);
            }
        }
    }
}
