//! A minimal, dialect-native HTTP layer over `prelude::{listen, accept,
//! Tcp}`'s raw sockets: request parsing, `{param}`-templated routing,
//! and an OpenAPI 3.0 document generated by `Router::dispatch` itself
//! for every service — `GET /openapi.json` always exists, with no
//! opt-in step.
//!
//! **Road 1 / Road 2 (RFC 0020).** A gated route's actual enforcement
//! is `Auth::prove::<R>()`, called once per request inside
//! `Router::{get,post,put,delete}_gated`, using the exact `RoleProof<R>`
//! mechanism `role.rs` already makes unforgeable. The OpenAPI
//! document's role annotation is a *read* of that same `R::NAME` —
//! captured at route-registration time, not independently declared —
//! so it is a derived, non-authoritative projection by construction: it
//! cannot drift from what is actually enforced, because there is only
//! one source (`R`), not two.

use std::collections::HashMap;
use std::rc::Rc;

use crate::role::{Auth, Role, RoleProof};

#[derive(Debug, Clone)]
pub struct Request {
    pub method: String,
    pub path: String,
    pub headers: HashMap<String, String>,
    pub body: String,
}

impl Request {
    pub fn header(&self, name: &str) -> Option<&str> {
        self.headers.get(&name.to_ascii_lowercase()).map(String::as_str)
    }

    /// Parse a raw HTTP/1.1 request exactly as `Tcp::recv()` hands it
    /// back: request line, headers, a blank line, then the body.
    pub fn parse(raw: &str) -> Option<Request> {
        let mut lines = raw.split("\r\n");
        let request_line = lines.next()?;
        let mut parts = request_line.split(' ');
        let method = parts.next()?.to_string();
        let path = parts.next()?.to_string();

        let mut headers = HashMap::new();
        let mut in_body = false;
        let mut body_lines = Vec::new();
        for line in lines {
            if in_body {
                body_lines.push(line);
                continue;
            }
            if line.is_empty() {
                in_body = true;
                continue;
            }
            if let Some((k, v)) = line.split_once(':') {
                headers.insert(k.trim().to_ascii_lowercase(), v.trim().to_string());
            }
        }
        Some(Request {
            method,
            path,
            headers,
            body: body_lines.join("\r\n"),
        })
    }

    fn path_without_query(&self) -> &str {
        self.path.split('?').next().unwrap_or(&self.path)
    }

    /// The parsed query string (`?a=1&b=2` → `{"a":"1","b":"2"}`).
    pub fn query(&self) -> HashMap<String, String> {
        match self.path.split_once('?') {
            Some((_, q)) => parse_urlencoded(q),
            None => HashMap::new(),
        }
    }

    /// The request body as key→value strings, regardless of whether it
    /// arrived as `application/json` (an API caller) or
    /// `application/x-www-form-urlencoded` (an ordinary HTML `<form>`
    /// POST — this dialect has no client-side JS, so every screen's
    /// form submits the plain browser default). One body shape, one
    /// parser either way — screens and the JSON API share the exact
    /// same create/update functions.
    pub fn form_or_json(&self) -> HashMap<String, String> {
        match self.header("content-type") {
            Some(ct) if ct.starts_with("application/json") => serde_json::from_str::<serde_json::Value>(&self.body)
                .ok()
                .and_then(|v| v.as_object().cloned())
                .map(|obj| obj.into_iter().map(|(k, v)| (k, json_scalar_to_string(&v))).collect())
                .unwrap_or_default(),
            _ => parse_urlencoded(&self.body),
        }
    }
}

fn json_scalar_to_string(v: &serde_json::Value) -> String {
    match v {
        serde_json::Value::String(s) => s.clone(),
        serde_json::Value::Null => String::new(),
        other => other.to_string(),
    }
}

fn parse_urlencoded(s: &str) -> HashMap<String, String> {
    s.split('&')
        .filter(|p| !p.is_empty())
        .filter_map(|pair| {
            let (k, v) = pair.split_once('=').unwrap_or((pair, ""));
            Some((url_decode(k), url_decode(v)))
        })
        .collect()
}

/// Percent-decodes into bytes first, then interprets as UTF-8 — naive
/// char-by-char decoding would corrupt any multi-byte percent-encoded
/// sequence (e.g. `%C3%A9`).
fn url_decode(s: &str) -> String {
    let mut bytes = Vec::new();
    let mut chars = s.chars();
    while let Some(c) = chars.next() {
        match c {
            '+' => bytes.push(b' '),
            '%' => {
                let hex: String = chars.by_ref().take(2).collect();
                match u8::from_str_radix(&hex, 16) {
                    Ok(byte) => bytes.push(byte),
                    Err(_) => bytes.extend_from_slice(hex.as_bytes()),
                }
            }
            c => {
                let mut buf = [0u8; 4];
                bytes.extend_from_slice(c.encode_utf8(&mut buf).as_bytes());
            }
        }
    }
    String::from_utf8_lossy(&bytes).into_owned()
}

/// Escapes `&`, `<`, `>`, `"`, `'` for safe interpolation into HTML —
/// every screen renderer routes user/entity data through this before
/// writing it into a page; nothing here ever trusts stored data to be
/// pre-sanitized.
pub fn html_escape(s: &str) -> String {
    s.replace('&', "&amp;")
        .replace('<', "&lt;")
        .replace('>', "&gt;")
        .replace('"', "&quot;")
        .replace('\'', "&#39;")
}

/// The one shared page template every server-rendered screen (and
/// `dashboard!`) wraps its body in — no client-side JS, no build step,
/// just enough CSS to make tables/forms/widgets legible.
pub fn page_shell(title: &str, extra_head: &str, body: &str) -> String {
    format!(
        "<!doctype html><html><head><meta charset=\"utf-8\"><title>{}</title>{extra_head}\
         <style>\
         body{{font-family:sans-serif;margin:2rem;color:#222}}\
         table{{border-collapse:collapse;width:100%}}th,td{{border:1px solid #ddd;padding:0.5rem;text-align:left}}\
         th{{background:#f5f5f5}}\
         .widget{{display:inline-block;vertical-align:top;margin:0 1.5rem 1.5rem 0;padding:1rem;border:1px solid #ccc;border-radius:6px}}\
         .metric .value{{font-size:2rem;font-weight:bold}}.metric.alert .value{{color:#c0392b}}\
         .metric .label,.chart .label{{color:#666;font-size:0.9rem}}\
         .empty{{color:#666;font-style:italic}}\
         form p{{margin:0.5rem 0}}label{{display:inline-block;width:10rem}}\
         .danger{{color:#c0392b}}.errors{{color:#c0392b}}\
         </style></head><body><h1>{}</h1>{body}</body></html>",
        html_escape(title),
        html_escape(title),
    )
}

#[derive(Debug, Clone)]
pub struct Response {
    pub status: u16,
    pub content_type: &'static str,
    pub body: String,
    pub extra_headers: Vec<(String, String)>,
}

impl Response {
    pub fn json(status: u16, value: &serde_json::Value) -> Response {
        Response {
            status,
            content_type: "application/json",
            body: value.to_string(),
            extra_headers: Vec::new(),
        }
    }

    pub fn text(status: u16, body: impl Into<String>) -> Response {
        Response {
            status,
            content_type: "text/plain",
            body: body.into(),
            extra_headers: Vec::new(),
        }
    }

    pub fn html(status: u16, body: impl Into<String>) -> Response {
        Response {
            status,
            content_type: "text/html; charset=utf-8",
            body: body.into(),
            extra_headers: Vec::new(),
        }
    }

    pub fn no_content() -> Response {
        Response {
            status: 204,
            content_type: "text/plain",
            body: String::new(),
            extra_headers: Vec::new(),
        }
    }

    pub fn not_found() -> Response {
        Response::text(404, "not found")
    }

    pub fn forbidden() -> Response {
        Response::text(403, "forbidden")
    }

    pub fn bad_request(msg: impl Into<String>) -> Response {
        Response::text(400, msg)
    }

    /// A 302 redirect — used by every screen's POST handler (create,
    /// update, delete) to send the browser to the resulting page
    /// instead of rendering a bare API response, since these are
    /// ordinary `<form>` submissions, not API calls.
    pub fn redirect(location: impl Into<String>) -> Response {
        Response {
            status: 302,
            content_type: "text/plain",
            body: String::new(),
            extra_headers: vec![("Location".to_string(), location.into())],
        }
    }

    fn write_to(&self, conn: &crate::prelude::Tcp) {
        let mut head = format!(
            "HTTP/1.1 {} {}\r\nContent-Type: {}\r\nContent-Length: {}\r\nConnection: close\r\n",
            self.status,
            reason_phrase(self.status),
            self.content_type,
            self.body.len(),
        );
        for (name, value) in &self.extra_headers {
            head.push_str(&format!("{name}: {value}\r\n"));
        }
        head.push_str("\r\n");
        conn.send(&head);
        conn.send(&self.body);
    }
}

fn reason_phrase(status: u16) -> &'static str {
    match status {
        200 => "OK",
        201 => "Created",
        204 => "No Content",
        400 => "Bad Request",
        403 => "Forbidden",
        404 => "Not Found",
        405 => "Method Not Allowed",
        500 => "Internal Server Error",
        _ => "Unknown",
    }
}

#[derive(Debug, Clone, Default)]
pub struct PathParams(HashMap<String, String>);

impl PathParams {
    pub fn get(&self, key: &str) -> Option<&str> {
        self.0.get(key).map(String::as_str)
    }
}

#[derive(Debug, Clone)]
enum Segment {
    Literal(String),
    Param(String),
}

#[derive(Debug, Clone)]
struct PathTemplate {
    segments: Vec<Segment>,
}

fn split_path(path: &str) -> Vec<&str> {
    path.trim_matches('/').split('/').filter(|s| !s.is_empty()).collect()
}

impl PathTemplate {
    fn parse(template: &str) -> PathTemplate {
        let segments = split_path(template)
            .into_iter()
            .map(|s| match s.strip_prefix('{').and_then(|s| s.strip_suffix('}')) {
                Some(name) => Segment::Param(name.to_string()),
                None => Segment::Literal(s.to_string()),
            })
            .collect();
        PathTemplate { segments }
    }

    fn matches(&self, path: &str) -> Option<PathParams> {
        let actual = split_path(path);
        if actual.len() != self.segments.len() {
            return None;
        }
        let mut params = HashMap::new();
        for (seg, value) in self.segments.iter().zip(actual.iter()) {
            match seg {
                Segment::Literal(lit) => {
                    if lit != value {
                        return None;
                    }
                }
                Segment::Param(name) => {
                    params.insert(name.clone(), value.to_string());
                }
            }
        }
        Some(PathParams(params))
    }

    fn as_openapi_path(&self) -> String {
        let rendered: Vec<String> = self
            .segments
            .iter()
            .map(|s| match s {
                Segment::Literal(l) => l.clone(),
                Segment::Param(p) => format!("{{{p}}}"),
            })
            .collect();
        format!("/{}", rendered.join("/"))
    }
}

type Handler = Box<dyn Fn(&Request, &PathParams) -> Response>;

struct Route {
    method: &'static str,
    template: PathTemplate,
    summary: &'static str,
    /// Road 2: a read of the `R::NAME` used for the *actual* gate at
    /// registration time. `None` for an ungated route. Never the other
    /// way around — nothing here can cause a route to be gated; it only
    /// documents a gate that already exists.
    required_role: Option<&'static str>,
    handler: Handler,
}

/// A request → `Response` router with OpenAPI baked into `dispatch`
/// itself. `authenticate` turns a request into a session (e.g. reading
/// an `Authorization` header via the app's own identity fixture) —
/// this crate has no opinion on token formats, only on what happens
/// once you have an `Auth`.
pub struct Router {
    title: &'static str,
    version: &'static str,
    routes: Vec<Route>,
    authenticate: Rc<dyn Fn(&Request) -> Auth>,
}

macro_rules! ungated_method {
    ($name:ident, $method:literal) => {
        pub fn $name(
            mut self,
            path: &'static str,
            summary: &'static str,
            handler: impl Fn(&Request, &PathParams) -> Response + 'static,
        ) -> Self {
            self.routes.push(Route {
                method: $method,
                template: PathTemplate::parse(path),
                summary,
                required_role: None,
                handler: Box::new(handler),
            });
            self
        }
    };
}

macro_rules! gated_method {
    ($name:ident, $method:literal) => {
        pub fn $name<R: Role + 'static>(
            mut self,
            path: &'static str,
            summary: &'static str,
            handler: impl Fn(&Request, &PathParams, &RoleProof<R>) -> Response + 'static,
        ) -> Self {
            let authenticate = self.authenticate.clone();
            let wrapped = move |req: &Request, params: &PathParams| -> Response {
                match authenticate(req).prove::<R>() {
                    Ok(proof) => handler(req, params, &proof),
                    Err(_) => Response::forbidden(),
                }
            };
            self.routes.push(Route {
                method: $method,
                template: PathTemplate::parse(path),
                summary,
                required_role: Some(R::NAME),
                handler: Box::new(wrapped),
            });
            self
        }
    };
}

impl Router {
    pub fn new(authenticate: impl Fn(&Request) -> Auth + 'static) -> Router {
        Router {
            title: "Nirdosha service",
            version: "0.1.0",
            routes: Vec::new(),
            authenticate: Rc::new(authenticate),
        }
    }

    pub fn with_info(mut self, title: &'static str, version: &'static str) -> Self {
        self.title = title;
        self.version = version;
        self
    }

    ungated_method!(get, "GET");
    ungated_method!(post, "POST");
    ungated_method!(put, "PUT");
    ungated_method!(delete, "DELETE");

    gated_method!(get_gated, "GET");
    gated_method!(post_gated, "POST");
    gated_method!(put_gated, "PUT");
    gated_method!(delete_gated, "DELETE");

    /// Route one already-parsed request. `GET /openapi.json` is
    /// answered here directly, before the route table — it always
    /// exists, computed fresh from the final route list, and cannot be
    /// shadowed by an app forgetting to register it.
    pub fn dispatch(&self, req: &Request) -> Response {
        let path = req.path_without_query();
        if req.method == "GET" && path == "/openapi.json" {
            return Response::json(200, &self.openapi_document());
        }
        let mut path_matched_some_method = false;
        for route in &self.routes {
            if let Some(params) = route.template.matches(path) {
                if route.method == req.method {
                    return (route.handler)(req, &params);
                }
                path_matched_some_method = true;
            }
        }
        if path_matched_some_method {
            Response::text(405, "method not allowed")
        } else {
            Response::not_found()
        }
    }

    /// A minimal OpenAPI 3.0.3 document: paths, methods, summaries, and
    /// — for a gated route — a `security` entry naming the role
    /// `R::NAME` that route's handler actually checked at registration
    /// time. Not a schema generator: request/response bodies are not
    /// typed here.
    pub fn openapi_document(&self) -> serde_json::Value {
        let mut paths = serde_json::Map::new();
        for route in &self.routes {
            let key = route.template.as_openapi_path();
            let entry = paths
                .entry(key)
                .or_insert_with(|| serde_json::json!({}))
                .as_object_mut()
                .expect("path entries are always objects");
            let mut op = serde_json::json!({
                "summary": route.summary,
                "responses": { "200": { "description": "OK" } },
            });
            if let Some(role) = route.required_role {
                op["security"] = serde_json::json!([{ "nirdoshaRole": [role] }]);
            }
            entry.insert(route.method.to_ascii_lowercase(), op);
        }
        serde_json::json!({
            "openapi": "3.0.3",
            "info": { "title": self.title, "version": self.version },
            "paths": serde_json::Value::Object(paths),
            "components": {
                "securitySchemes": {
                    "nirdoshaRole": {
                        "type": "apiKey",
                        "in": "header",
                        "name": "X-Nirdosha-Role-Doc",
                        "description": "Documentation only, mirroring the RoleProof<R> type actually enforced server-side (RFC 0020 Road 1/Road 2). Never authoritative on its own."
                    }
                }
            }
        })
    }

    /// Serve forever on `127.0.0.1:port` — one connection at a time,
    /// same simplification `51_compiled_serve.nir` already makes (a
    /// single `recv()` read per request; no keep-alive).
    pub fn serve(&self, port: u16) -> ! {
        let listener = crate::prelude::listen(port as i64);
        loop {
            let conn = crate::prelude::accept(&listener);
            let raw = conn.recv();
            let response = match Request::parse(&raw) {
                Some(req) => self.dispatch(&req),
                None => Response::bad_request("malformed request"),
            };
            // A client that disconnects mid-response (a closed tab, a
            // cancelled prefetch, an aggressive timeout) must not take
            // the whole server down with it. `Tcp::send` panics on a
            // broken pipe — the right behavior for `.nir`'s own
            // send/recv contract, where a write failure usually means a
            // real bug — but a long-running HTTP server sees this
            // condition routinely and must survive it, the same way
            // `Tcp::recv` already tolerates a closed peer. Isolating
            // just this connection's write behind `catch_unwind` gets
            // that survival without changing `Tcp::send`'s panic
            // contract for every other caller in the dialect.
            let _ = std::panic::catch_unwind(std::panic::AssertUnwindSafe(|| {
                response.write_to(&conn);
            }));
            crate::prelude::stop(conn);
        }
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    struct Admin;
    impl Role for Admin {
        const NAME: &'static str = "admin";
    }

    #[test]
    fn parses_method_path_headers_and_body() {
        let raw = "POST /api/products HTTP/1.1\r\nHost: x\r\nAuthorization: Bearer tok\r\n\r\n{\"name\":\"Widget\"}";
        let req = Request::parse(raw).unwrap();
        assert_eq!(req.method, "POST");
        assert_eq!(req.path, "/api/products");
        assert_eq!(req.header("authorization"), Some("Bearer tok"));
        assert_eq!(req.body, "{\"name\":\"Widget\"}");
    }

    #[test]
    fn query_string_is_parsed() {
        let req = Request {
            method: "GET".into(),
            path: "/api/products?q=widget&page=2".into(),
            headers: HashMap::new(),
            body: String::new(),
        };
        let q = req.query();
        assert_eq!(q.get("q"), Some(&"widget".to_string()));
        assert_eq!(q.get("page"), Some(&"2".to_string()));
    }

    #[test]
    fn form_urlencoded_body_is_parsed_with_percent_decoding() {
        let req = Request {
            method: "POST".into(),
            path: "/api/products".into(),
            headers: HashMap::new(),
            body: "name=Caf%C3%A9+Table&price_cents=999".into(),
        };
        let form = req.form_or_json();
        assert_eq!(form.get("name"), Some(&"Café Table".to_string()));
        assert_eq!(form.get("price_cents"), Some(&"999".to_string()));
    }

    #[test]
    fn json_body_is_parsed_the_same_way_form_is() {
        let mut headers = HashMap::new();
        headers.insert("content-type".to_string(), "application/json".to_string());
        let req = Request {
            method: "POST".into(),
            path: "/api/products".into(),
            headers,
            body: r#"{"name":"Widget","price_cents":999}"#.into(),
        };
        let form = req.form_or_json();
        assert_eq!(form.get("name"), Some(&"Widget".to_string()));
        assert_eq!(form.get("price_cents"), Some(&"999".to_string()));
    }

    #[test]
    fn html_escape_neutralizes_markup() {
        assert_eq!(html_escape("<script>alert('x')</script>"), "&lt;script&gt;alert(&#39;x&#39;)&lt;/script&gt;");
    }

    #[test]
    fn path_template_extracts_params() {
        let t = PathTemplate::parse("/api/products/{id}");
        let params = t.matches("/api/products/42").unwrap();
        assert_eq!(params.get("id"), Some("42"));
        assert!(t.matches("/api/products").is_none());
        assert!(t.matches("/api/products/42/extra").is_none());
    }

    fn req(method: &str, path: &str) -> Request {
        Request {
            method: method.into(),
            path: path.into(),
            headers: HashMap::new(),
            body: String::new(),
        }
    }

    #[test]
    fn unknown_path_is_404_known_path_wrong_method_is_405() {
        let router = Router::new(|_| Auth::login("anon", &[])).get("/api/products", "list", |_, _| Response::text(200, "ok"));
        assert_eq!(router.dispatch(&req("GET", "/nope")).status, 404);
        assert_eq!(router.dispatch(&req("POST", "/api/products")).status, 405);
        assert_eq!(router.dispatch(&req("GET", "/api/products")).status, 200);
    }

    #[test]
    fn openapi_json_always_exists_with_no_registration() {
        let router = Router::new(|_| Auth::login("anon", &[]));
        let resp = router.dispatch(&req("GET", "/openapi.json"));
        assert_eq!(resp.status, 200);
        let doc: serde_json::Value = serde_json::from_str(&resp.body).unwrap();
        assert_eq!(doc["openapi"], "3.0.3");
    }

    #[test]
    fn gated_route_enforces_the_real_role_proof() {
        let router = Router::new(|r| {
            let roles: Vec<&str> = r.header("x-roles").map(|s| s.split(',').collect()).unwrap_or_default();
            Auth::login("user", &roles)
        })
        .post_gated::<Admin>("/api/products", "create", |_, _, _proof| Response::text(201, "created"));

        let mut denied = req("POST", "/api/products");
        assert_eq!(router.dispatch(&denied).status, 403);

        denied.headers.insert("x-roles".into(), "admin".into());
        assert_eq!(router.dispatch(&denied).status, 201);
    }

    #[test]
    fn openapi_reports_the_same_role_the_gate_checked() {
        let router = Router::new(|_| Auth::login("anon", &[]))
            .post_gated::<Admin>("/api/products", "create", |_, _, _proof| Response::text(201, "created"));
        let doc = router.openapi_document();
        let role = &doc["paths"]["/api/products"]["post"]["security"][0]["nirdoshaRole"][0];
        assert_eq!(role, "admin");
    }

    // -------------------------------------------------------------------
    // Property-based tests. White-box (this module's own `PathTemplate`),
    // not just the handful of examples above.
    // -------------------------------------------------------------------
    mod properties {
        use super::*;
        use proptest::prelude::*;

        fn segment_strategy() -> impl Strategy<Value = String> {
            "[a-z][a-z0-9_]{1,8}"
        }

        fn percent_encode(s: &str) -> String {
            s.bytes()
                .map(|b| match b {
                    b'A'..=b'Z' | b'a'..=b'z' | b'0'..=b'9' | b'-' | b'_' | b'.' | b'~' => (b as char).to_string(),
                    _ => format!("%{b:02X}"),
                })
                .collect()
        }

        proptest! {
            /// Percent-decoding round-trips arbitrary Unicode strings
            /// through an ordinary percent-encoder — the byte-buffer
            /// decode (not a naive char-by-char one) has to get
            /// multi-byte UTF-8 right, not just ASCII.
            #[test]
            fn url_decode_round_trips_arbitrary_strings(s in ".*") {
                let form = format!("k={}", percent_encode(&s));
                let parsed = parse_urlencoded(&form);
                prop_assert_eq!(parsed.get("k").map(String::as_str), Some(s.as_str()));
            }

            /// html_escape's output never contains a raw `<` or `>`,
            /// for any input — the property that actually makes it
            /// safe to interpolate into HTML.
            #[test]
            fn html_escape_leaves_no_raw_markup_delimiters(s in ".*") {
                let escaped = html_escape(&s);
                prop_assert!(!escaped.contains('<'));
                prop_assert!(!escaped.contains('>'));
            }
        }

        proptest! {
            /// For any literal path built from arbitrary segments, the
            /// template built from those exact literal segments matches
            /// that path and extracts no params.
            #[test]
            fn literal_template_matches_its_own_path(segs in prop::collection::vec(segment_strategy(), 1..5)) {
                let path = format!("/{}", segs.join("/"));
                let template = PathTemplate::parse(&path);
                let params = template.matches(&path);
                prop_assert!(params.is_some());
            }

            /// A `{param}` segment always extracts exactly the concrete
            /// value that occupied that position, for any concrete value
            /// that itself looks like an ordinary path segment.
            #[test]
            fn param_segment_extracts_the_concrete_value(
                prefix in segment_strategy(),
                param_name in segment_strategy(),
                value in segment_strategy(),
            ) {
                let template = PathTemplate::parse(&format!("/{prefix}/{{{param_name}}}"));
                let params = template.matches(&format!("/{prefix}/{value}")).unwrap();
                prop_assert_eq!(params.get(&param_name), Some(value.as_str()));
            }

            /// Changing any literal segment to a different literal never
            /// matches.
            #[test]
            fn mismatched_literal_never_matches(
                seg in segment_strategy(),
                other in segment_strategy(),
            ) {
                prop_assume!(seg != other);
                let template = PathTemplate::parse(&format!("/api/{seg}"));
                let other_path = format!("/api/{other}");
                let no_match = template.matches(&other_path).is_none();
                prop_assert!(no_match);
            }

            /// A gated route's real enforcement (`Auth::prove::<Admin>()`
            /// via the router) succeeds if and only if the session's role
            /// set actually contains `"admin"` — the property this whole
            /// mechanism exists for. Fuzzed over arbitrary role-set
            /// contents, not just the one hand-picked example above.
            #[test]
            fn gated_dispatch_succeeds_iff_role_present(
                roles in prop::collection::vec(segment_strategy(), 0..4),
            ) {
                let has_admin = roles.iter().any(|r| r == "admin");
                let router = Router::new(move |r: &Request| {
                    let roles: Vec<&str> = r.header("x-roles").map(|s| s.split(',').filter(|s| !s.is_empty()).collect()).unwrap_or_default();
                    Auth::login("user", &roles)
                })
                .post_gated::<Admin>("/api/products", "create", |_, _, _proof| Response::text(201, "created"));

                let mut request = req("POST", "/api/products");
                request.headers.insert("x-roles".into(), roles.join(","));
                let status = router.dispatch(&request).status;
                prop_assert_eq!(status == 201, has_admin);
                prop_assert!(status == 201 || status == 403);
            }

            /// Any request whose path doesn't match a registered route's
            /// template is always 404, regardless of method.
            #[test]
            fn unregistered_path_is_always_404(
                registered in segment_strategy(),
                requested in segment_strategy(),
                method in "GET|POST|PUT|DELETE",
            ) {
                prop_assume!(registered != requested);
                let path: &'static str = Box::leak(format!("/{registered}").into_boxed_str());
                let router = Router::new(|_| Auth::login("anon", &[]))
                    .get(path, "x", |_, _| Response::text(200, "ok"));
                let status = router.dispatch(&req(&method, &format!("/{requested}"))).status;
                prop_assert_eq!(status, 404);
            }
        }
    }
}
