#!/usr/bin/env python3
"""Regenerates src/logo_pixels.rs from assets/brand/nirdosha-logo.png.

Samples the icon glyph (the wordmark below it is cropped out -- real
terminal text renders crisper than raster text ever could, so
`logo_anim.rs` draws "NIRDOSHA" / "PROGRAMMING LANGUAGE" as actual
styled text instead) down to a CHAR_W x CHAR_H character grid, two
vertical pixel samples per character row -- the classic half-block
trick (foreground = top sample, background = bottom sample, rendered
as '▀') that roughly cancels a terminal cell's ~1:2 width:height aspect
ratio and gives near-square effective pixels.

Usage: python3 gen_logo_pixels.py   (needs Pillow: pip install pillow)
Run from anywhere -- paths below are relative to this file.
"""

from pathlib import Path
from PIL import Image

HERE = Path(__file__).resolve().parent
SRC = HERE / "../../assets/brand/nirdosha-logo.png"
OUT = HERE / "src/logo_pixels.rs"

CHAR_W = 44
CHAR_H = 44

# Bounding box of just the icon glyph within the source PNG (572x580),
# found by scanning for background-only rows/columns -- see the RFC/PR
# description for the exact method. Re-crop by hand if the source art
# changes.
CROP = (150, 62, 462, 375)

BG_THRESHOLD = 232  # r,g,b all above this -> treated as background (skipped)


def is_bg(px):
    r, g, b = px
    return r > BG_THRESHOLD and g > BG_THRESHOLD and b > BG_THRESHOLD


def main():
    im = Image.open(SRC).convert("RGB")
    crop = im.crop(CROP)
    # 2 vertical samples per character row (half-block trick), 1 per column.
    sample = crop.resize((CHAR_W, CHAR_H * 2), Image.LANCZOS)

    def cell(x, y):
        px = sample.getpixel((x, y))
        return None if is_bg(px) else px

    lines = [
        "// Generated by gen_logo_pixels.py from assets/brand/nirdosha-logo.png.",
        "// Do not hand-edit -- re-run the generator instead.",
        f"pub const LOGO_W: usize = {CHAR_W};",
        f"pub const LOGO_H: usize = {CHAR_H};",
        "pub type Px = Option<(u8, u8, u8)>;",
        # One source line per image row on purpose (each line's shape
        # loosely echoes the row it encodes) -- `#[rustfmt::skip]` keeps
        # `cargo fmt` from exploding it into one entry per line.
        "#[rustfmt::skip]",
        "pub const LOGO: [[(Px, Px); LOGO_W]; LOGO_H] = [",
    ]
    for row in range(CHAR_H):
        cells = []
        for col in range(CHAR_W):
            top = cell(col, row * 2)
            bot = cell(col, row * 2 + 1)

            def fmt(p):
                return "None" if p is None else f"Some(({p[0]}, {p[1]}, {p[2]}))"

            cells.append(f"({fmt(top)}, {fmt(bot)})")
        lines.append("    [" + ", ".join(cells) + "],")
    lines.append("];")

    OUT.write_text("\n".join(lines) + "\n")
    print(f"wrote {OUT}")


if __name__ == "__main__":
    main()
